backCompatKeys:  
  #Group name already exists
  IAM.GROUP.NAME.EXISTS : IAM.ERROR.CODE.G103
  
  #Invalid X.509 certificate. Please try again
  IAM.SAML.ERROR.INVALID.CERTIFICATE : IAM.ERROR.CODE.O122
  
  #Device (or) app name already exists
  IAM.TFA.DEVICENAME.EXIST : IAM.ERROR.CODE.TFA101
  
  #Limit exceeded. Please remove old application passwords
  IAM.APP.PASSWORD.LIMIT.EXCEEDED : IAM.ERROR.CODE.TFA103
  
  #Invalid password
  IAM.ERROR.INVALID.PASS : IAM.ERROR.CODE.U110
  IAM.ERROR.INVALID_PASSWORD : IAM.ERROR.CODE.U110
  IAM.ERROR.INVITATION.PASSWORD.INVALID : IAM.ERROR.CODE.U110
  IAM.TFA.INVALID.PASSWORD : IAM.ERROR.CODE.U110
  
  #Email address cannot contain the \u2018+\u2019 character.
  IAM.ORG.USER.INVITATION.ERROR.EMAIL.SPECIAL.CHARACTER : IAM.ERROR.CODE.U131
  
  #User Guide
  IAM.USERGUIDE : IAM.USER.GUIDE
  
  #Developer Guide
  IAM.DEVELOPERGUIDE : IAM.DEVELOPER.GUIDE
  
  #FAQs
  IAM.FAQ : IAM.HEADER.FAQ
  
  #Sign Out
  IAM.LOGOUT : IAM.SIGN.OUT
  
  #User ID
  IAM.TOPBAR.USER.ID : IAM.USER.ID
  
  #OK
  IAM.CONTACTS.OK : IAM.OK
  IAM.TFA.OK : IAM.OK
  
  #Verify
  IAM.BUTTON.VERIFY : IAM.NEW.SIGNIN.VERIFY
  IAM.TFA.VERIFY : IAM.NEW.SIGNIN.VERIFY
  IAM.VERIFY : IAM.NEW.SIGNIN.VERIFY
  IAM.DEVICEOAUTH.VERIFY : IAM.NEW.SIGNIN.VERIFY
  
  #Next
  IAM.TFA.NEXT : IAM.NEXT
  
  #Submit
  IAM.BUTTON.SUBMIT : IAM.SUBMIT
  
  #Confirm
  IAM.USER.PROFILE.REVIEW.YES.PROCEED : IAM.CONFIRM
  
  #Verify OTP
  IAM.VERIFY.OTP : IAM.VERIFY.LABEL
  IAM.VERIFY.OTP.HEADING : IAM.VERIFY.LABEL
  
  #Continue
  IAM.TEMPLATE.ORG.INVITATION.SUCESS.CONTINUE : IAM.CONTINUE
  IAM.TFA.BANNER.CONTINUE : IAM.CONTINUE
  
  #Redirect Now
  IAM.FEDERATE.LOGOUT.REDIRECT.NOW : IAM.REDIRECT.NOW
  
  #SMS-based OTP
  IAM.MFA.ANNOUN.SMS.HEAD : IAM.TFA.SMS.HEAD
  
  #First Name
  IAM.GENERAL.FIRSTNAME : IAM.FIRST.NAME
  
  #Last Name
  IAM.GENERAL.LASTNAME : IAM.LAST.NAME
  
  #Device
  IAM.ALERT.SHOW.DEVICE : IAM.DEVICE
  
  #Try Again
  IAM.ONEAUTH.LOCKED.TRY.AGAIN : IAM.TRY.AGAIN
  IAM.YUBIKEY.TRY.AGAIN : IAM.TRY.AGAIN
  
  #Do it later
  IAM.APP.SESSION.MAX.LIMIT.LATER : IAM.DOIT.LATER
  
  #Email Address
  IAM.EMAIL.ADDR : IAM.EMAIL.ADDRESS
  
  #Change
  IAM.PHOTO.CHANGE : IAM.SIGNUP.CHANGE
  
  #Groups
  IAM.ORG.GROUPS : IAM.GROUPS
  
  #Only myself
  IAM.PHOTO.PERMISSION.ONLY.MYSELF : IAM.PHOTO.PERMISSION.ONLY_MYSELF
  
  #{0} characters
  IAM.ACCOUNTCONFIRM.PASSWORD.CHARACTER : IAM.RESETPASS.PASSWORD.MIN.NO.WITH
  IAM.RESETPASS.PASSWORD.MIN.ONLY : IAM.RESETPASS.PASSWORD.MIN.NO.WITH
  
  #Both upper and lower case letters
  IAM.RESET.PASSWORD.POLICY.CASE.BOTH : IAM.PASS_POLICY.CASE
  
  #From IP address cannot be empty
  IAM.ALLOWEDIP.FROMIP.EMPTY : IAM.ALLOWEDIP.FROMIP.ERROR.EMPTY
  
  #Please enter valid To IP address
  IAM.ALLOWEDIP.TOIP.NOTVALID : IAM.ALLOWEDIP.TOIP.NOT_VALID
  
  #Please enter valid name
  IAM.TFA.YUBIKEY.ERRMSG : IAM.ALLOWEDIP.NAME.NOTVALID
  
  #Your organization does not allow you to generate App password for your account. Contact your administrator.
  IAM.APP.PASSWORD.ORG.RESTRICTION : IAM.APP.PASSWORD.GENERATION.RESTRICTED
  
  #Disabling MFA will significantly reduce your account security. If you choose to <span style : 'white-space:nowrap;'>re-enable</span> it, you will have to reconfigure app-specific passwords and generate new backup codes.
  IAM.TFA.DELETE.TXT : IAM.MFA.DISABLE.TXT
  
  #Disabled
  IAM.DEVELOPERCONSOLE.ZOHO.DISABLED : IAM.MFA.MODE.DISABLED
  
  #Generated on
  IAM.MFA.BACKUPCODE.FILE.GENERATED.TIME : IAM.GENERATE.ON
  
  #Generate
  IAM.GENERATE.NOW : IAM.TFA.GENERATE
  
  #Each code can be used only once.
  IAM.MFA.BACKUPCODE.FILE.NOTES1 : IAM.LIST.BACKUPCODES.POINT1
  
  #Do not share these codes with anyone.
  IAM.MFA.BACKUPCODE.FILE.NOTES2 : IAM.LIST.BACKUPCODES.POINT3
  
  #Backup verification codes allow you to access your $REBRAND_PARTNER_NAME account when you''re having trouble signing in.
  IAM.TFA.BKP.DESCRIPTION : IAM.LIST.BACKUPCODES.NOTICE
  
  #Enter Email Address
  IAM.AC.SEND.EMAIL : IAM.ENTER.EMAIL
  IAM.NEW.SIGNIN.VERIFY.EMAIL.PLACEHOLDER : IAM.ENTER.EMAIL
  
  #OTP Authenticator
  IAM.MFA.ANNOUN.TOTP.HEAD : IAM.GOOGLE.AUTHENTICATOR
  IAM.TIME.AUTHENTICATOR : IAM.GOOGLE.AUTHENTICATOR
  IAM.TIME.BASED.OTP : IAM.GOOGLE.AUTHENTICATOR
  IAM.TOTP.TIME.BASED.OTP : IAM.GOOGLE.AUTHENTICATOR
  
  #Use time-based OTPs generated by authenticator apps to securely sign in to your $REBRAND_PARTNER_NAME account.
  IAM.USE.AUTH.APP.DESC : IAM.TFA.BANNER.GOOGLE.AUTHENTICATOR.DESCRIPTION
  
  #Verify Email Address
  IAM.VERIFY.EMAIL.NOW : IAM.PROFILE.EMAIL.VERIFY.HEADING
  
  #Go to Linked Accounts
  IAM.PASSWORD.GO.TO.LINKED.ACCOUNTS : IAM.PROFILE.LINKED.ACCOUNT.SETTINGS
  
  #iOS
  IAM.IOS : IAM.OS.NAME.IOS
  
  #Only registered $REBRAND_PARTNER_NAME users
  IAM.PHOTO.PERMISSION.ZOHO.USERS : IAM.PHOTO.PERMISSION.ZOHO_USERS
  
  #Location
  IAM.ALERT.SHOW.REGION : IAM.AUTHORIZED.WEBSITES.TRUSTED.LOCATION
  
  #Data Processing Addendum
  IAM.GDPR.DPA.NAV.SUBHEAD : IAM.GDPR.DPA
  
  #State
  IAM.ANNOUNCEMENT.LOCALE.STATE.TITLE : IAM.GDPR.DPA.ADDRESS.STATE
  
  #All Cloud services of Zoho, ManageEngine, Site24x7, TrainerCentral and Qntrl.
  IAM.PRIVACY.CERTIFICATIONS.ISO27018.DESCRIPTION.APPLICABLETO : IAM.PRIVACY.CERTIFICATIONS.ISO27017.DESCRIPTION.APPLICABLETO
  
  #Send Email
  IAM.MSG.POPUP.SENDMAIL.TEXT : IAM.EMAIL.CONFIRMATION.SEND.EMAIL
  
  #Resend OTP
  IAM.MOBILE.RESEND.CONFIRMATION.OTP : IAM.NEW.SIGNIN.RESEND.OTP
  IAM.SECONDARY.EMAIL.RESEND.OTP : IAM.NEW.SIGNIN.RESEND.OTP
  IAM.SIGNUP.RESEND.OTP : IAM.NEW.SIGNIN.RESEND.OTP
  IAM.TFA.RESEND.OTP : IAM.NEW.SIGNIN.RESEND.OTP
  
  #Account password updated
  IAM.RESETPASSWORD.SUCCESS.RESET : IAM.PASSWORD.SUCCESS.RESET
  
  #Enter your password
  IAM.USER.EMAIL.ADD.PASSWORD.PLACEHOLDER : IAM.ENTER.PASS
  
  #Enter password
  IAM.ENTER.PASSWORD : IAM.NEW.SIGNIN.PASSWORD
  
  #You are not allowed to perform this operation. Please contact your admin.
  IAM.CLOSE.ACCOUNT.ERROR.NOT.SUPPORTED : IAM.GROUP.CREATE.ERROR.NO.PERMISSION
  
  #Invalid current password
  IAM.ERROR.INVALID.CURRENTPASS : IAM.ERROR.INVALID.CURRENT.PASSWORD
  
  #Please enter a valid email address
  IAM.ERROR.ENTER.SIGNUP.EMAIL : IAM.ERROR.EMAIL.INVALID
  IAM.ERROR.ENTER.VALID.EMAIL : IAM.ERROR.EMAIL.INVALID
  
  #Email address cannot be more than {0} characters
  IAM.ERROR.EMAIL.MAXLEN : IAM.ERROR.EMAIL.MAX.LENGTH
  
  #Full Name cannot be more than {0} characters
  IAM.ERROR.FNAME.MAXLEN : IAM.ERROR.FULLNAME.MAXLEN
  
  #Display name cannot be more than {0} characters
  IAM.ERROR.DISPLAYNAME.MAXLEN : IAM.ERROR.DISPLAYNAME.MAX.LENGTH
  
  #Updated successfully
  IAM.ACTIVETOKEN.REGENERATE.SUCCESS : IAM.ERROR.UPDATE.SUCCESS.MESSAGE
  IAM.UPLOAD.PHOTO.SUCCESS : IAM.ERROR.UPDATE.SUCCESS.MESSAGE
  
  #Group Name cannot be more than {0} characters
  IAM.ERROR.GROUPNAME.MAXLEN : IAM.ERROR.GROUPNAME.MAXIMUM.LENGTH
  IAM.ERROR.GROUPDESC.MAXLEN : IAM.ERROR.GROUPDESC.MAXIMUM.LENGTH
  
  #Invalid group name
  IAM.ERROR.INVALID.GRPNAME : IAM.GROUP.CREATE.ERROR.INVALID.GROUP
  
  #Group member deleted
  IAM.GROUP.DELETE.MEMBER.SUCCESS.REMOVE : IAM.GROUPSMEMBERS.DELETE.SUCESS.REMOVE
  
  #Please invite at least one user to create a group
  IAM.GROUP.UPDATE.ERROR.INVITATION_LIST.EMPTY : IAM.GROUP.CREATE.ERROR.NO.INVITATIONS
  
  #This group does not exist
  IAM.GROUP.DELETE.ERROR.INVALID.GROUP : IAM.GROUP.UPDATE.ERROR.INVALID.GROUP
  
  #Retry
  IAM.NEW.SIGNIN.RETRY.YUBIKEY : IAM.EXCEPTION.RELOAD
  
  #OTP sent to {0}
  IAM.MOBILE.VERIFICATION.OTP.SENT.MSG : IAM.NEW.SIGNIN.OTP.SENT
  IAM.SETUP.TFA.VERIFY_MOBILE.DESC : IAM.NEW.SIGNIN.OTP.SENT
  
  #Sign in using SAML
  IAM.SIGNIN.SAML.USER : IAM.NEW.SIGNIN.USING.SAML
  
  #Incorrect verification code. Please try again.
  IAM.MFA.EXO.ERROR.INVALID.VERIFY.CODE : IAM.PHONE.INVALID.BACKUP.CODE
  IAM.MFA.TOTP.ERROR.INVALID.VERIFY.CODE : IAM.PHONE.INVALID.BACKUP.CODE
  
  #Sign in using Google
  IAM.SIGNIN.IDP.GOOGLE : IAM.FEDERATED.SIGNIN.GOOGLE
  
  #Sign in using Facebook
  IAM.SIGNIN.IDP.FACEBOOK : IAM.FEDERATED.SIGNIN.FACEBOOK
  
  #Sign in using Yahoo
  IAM.SIGNIN.IDP.YAHOO : IAM.FEDERATED.SIGNIN.YAHOO
  
  #A new $REBRAND_PARTNER_NAME account will be created for the email address <b>{0}</b>.
  IAM.ORGINVITATION.SIGNUP.DEFINITION : IAM.FEDERATED.SIGNUP.PAGE.EMAIL.DESC
  
  #Create Account
  IAM.SIGNUP.CREATE.AN.ACCOUNT : IAM.FEDERATED.SIGNUP.CREATE.ACCOUNT.BUTTON
  
  #Verify your email address
  IAM.HOSTED.EMAIL.PREANNOUNCEMENT.MAIL.TITLE : IAM.FEDERATED.SIGNUP.VERIFY.OTP.HEADER.EMAIL
  IAM.PROFILE.EMAIL.SEND.VERIFY.MAIL : IAM.FEDERATED.SIGNUP.VERIFY.OTP.HEADER.EMAIL
  
  #Sign in with $REBRAND_PARTNER_NAME
  IAM.SIGNIN.WITH.ZOHO : IAM.NEW.SIGNIN.USING.ZOHO
  
  #Sign in another way
  IAM.NEW.SIGNIN.CHOOSE.OTHER.WAY : IAM.NEW.SIGNIN.TRY.ANOTHERWAY
  
  #Invalid Input
  IAM.RESERVE.INVALID.INPUT : IAM.ERROR.INVALID.INPUT
  
  #Invalid OTP
  IAM.EMAIL.ERROR.INVALID.OTP : IAM.GENERAL.ERROR.INVALID.OTP
  
  #Please enter a valid OTP
  IAM.ERROR.ENTER.VALID.OTP : IAM.ERROR.VALID.OTP
  
  #URL should start with http or https
  IAM.SAMLSETUP.URL.PATTERN : IAM.SAML.SETUP.URL.PATTERN
  
  #Go to Domains
  IAM.REVERIFY.DOMAIN.REVERIFY.DOMAINS : IAM.SAMLSETUP.JIT.GO.TO.DOMAINS
  
  #Enter your email address
  IAM.USER.ADD.EMAIL.PLACEHOLDER : IAM.USER.ENTER.EMAIL.PLACEHOLDER
  
  #Invalid Operation
  IAM.MFA.BROWSER.ERROR.INVALID.TOKEN : IAM.MOBILE.ERROR.MOBILE.NOT.EXISTS
  IAM.MFA.TOTP.ERROR.DELETE.INVALID.SECRET.KEY : IAM.MOBILE.ERROR.MOBILE.NOT.EXISTS
  IAM.MFA.YUBIKEY.ERROR.DELETE.INVALID.YUBIKEY : IAM.MOBILE.ERROR.MOBILE.NOT.EXISTS
  
  #MFA Disabled
  IAM.ONEAUTH.SUCCESS.DISABLED : IAM.MFA.SUCCESS.DISABLED
  IAM.PUSH.TITLE.MFA.DISABLED.ALERT : IAM.MFA.SUCCESS.DISABLED
  
  #Primary device updated
  IAM.ONEAUTH.SUCCESS.CHANGE.PRIMARY : IAM.MFA.DEVICE.SUCCESS.PRIMARY.CHANGE
  
  #Continue to sign in
  IAM.CONFIRMATION.CONTINUE : IAM.AC.PASSWORD.MATCHED.SIGNIN.REDIRECT
  
  #Authenticator app
  IAM.AUTHENTICATR.APP : IAM.NEW.SIGNIN.VERIFY.VIA.AUTHENTICATOR
  IAM.NEW.MFA.AUTHENTICATOR.APP : IAM.NEW.SIGNIN.VERIFY.VIA.AUTHENTICATOR
  
  #SMS Verification
  IAM.NEW.SIGNIN.VERIFY.VIA.OTP : IAM.NEW.SIGNIN.SMS.MODE
  
  #OneAuth
  IAM.MFA.BANNER.ONE.AUTH.RECOMMENDED.TITLE : IAM.NEW.SIGNIN.VERIFY.VIA.ONEAUTH
  IAM.ONE.AUTH.APP : IAM.NEW.SIGNIN.VERIFY.VIA.ONEAUTH
  
  #Enter OTP
  IAM.NEW.SIGNIN.OTP : IAM.VERIFY.CODE
  IAM.TFA.ENTER.OTP.CODE : IAM.VERIFY.CODE
  
  #Session expired. Please refresh the page and sign in again.
  IAM.SIGNIN.ERROR.INVALID.DIGEST : IAM.SIGNIN.ERROR.INVALID.TEMP.TOKEN
  
  #Incorrect password. Please try again.
  IAM.PASSWORD.ERROR.INCORRECT : IAM.SIGNIN.ERROR.INVALID.PASSWORD
  
  #Incorrect OTP. Please try again.
  IAM.GENERAL.OTP.WRONG : IAM.SIGNIN.ERROR.INVALID.VERIFICATION.CODE
  IAM.MFA.MOBILE.ERROR.INVALID.VERIFY.CODE : IAM.SIGNIN.ERROR.INVALID.VERIFICATION.CODE
  IAM.PHONE.INVALID.VERIFY_CODE : IAM.SIGNIN.ERROR.INVALID.VERIFICATION.CODE
  
  #Set Password
  IAM.SET.PASSWORD : IAM.NEW.SIGNIN.PASSWORD.EXPIRED.SET
  
  #Domains
  IAM.ORG.DOMAINS : IAM.HEADER.DOMAINS
  
  #Unverified domain
  IAM.USER.VERIFY.DOMAIN.UNVERIFIED.DOMAIN.SINGLE : IAM.DOMAIN.UNVERIFIED
  
  #Expired domain
  IAM.REVERIFY.DOMAIN.EXPIRED.DOMAIN.SINGLE : IAM.DOMAIN.EXPIRED
  
  #Name (Host/Alias/TXT)
  IAM.ORG.DOMAIN.POPUP.CNAME.NAME : IAM.ORG.DOMAIN.POPUP.TEXT.HOST.NAME
  
  #Values (Point to/Destination)
  IAM.ORG.DOMAIN.POPUP.CNAME.VALUE : IAM.ORG.DOMAIN.POPUP.TEXT.HOST.VALUE
  
  #Please select the country/region
  IAM.GDPR.DPA.COUNTRY.ERROR : IAM.ANNOUNCEMENT.LOCALE.SELECT.COUNTRY
  
  #Mobile linked to too many accounts
  IAM.TFA.BANNER.MOBILE.COUNT.EXCEEDED : IAM.ERROR.CODE.U132
  
  #This mobile number is already associated with a different account.
  IAM.MOBILE.SCREENNAME.ERROR.EXISTS.IN.ANOTHER.DC : IAM.MOBILE.SCREENNAME.ERROR.NUMBER.ALREADY.EXIST
  
  #Session expired. Please try again.
  IAM.SECONDARY.EMAIL.TOKEN.EXPIRED : IAM.OPENID.SESSION.EXPIRED
  IAM.SORG.INVITAION.EXPIRY.CONTENT : IAM.ORG.INVITAION.EXPIRY.CONTENT
  
  #Invitation to join the organization!
  IAM.MAIL.SORG.INVITE.SUBJECT : IAM.MAIL.ORG.INVITE.SUBJECT
  
  #You have been invited by the admin of the <b>{0}</b> to join their organization. Click below to either accept or reject the invitation.
  IAM.MAIL.SORG.INVITE.SUBHEADER : IAM.MAIL.ORG.INVITE.SUBHEADER
  
  #Note: By accepting the invitation you''re agreeing that the admin can have access to your organization account details. The admin can perform actions like changing your personal information, reset password, change preferred MFA modes, etc.
  IAM.MAIL.SORG.INVITE.NOTE : IAM.MAIL.ORG.INVITE.NOTE
  
  #View Invitation
  IAM.MAIL.ORGINVITATION.TOACCEPT : IAM.MAIL.SORGINVITATION.TOACCEPT
  
  #Verify Password
  IAM.TFA.VERIFY.PASSWORD : IAM.AC.VERIFY.PASSWORD
  
  #Send an email to <a href : "mailto:{0}" style : "color:#0091FF;text-decoration:none;">{0}</a>  and we will assist you in recovering your account.
  IAM.AC.CONTACT.SUPPORT.DESC : IAM.AC.CONTACT.SUPPORT.NO_OPTION.CONTACT
  
  #Verify via mobile number
  IAM.RELOGIN.VERIFY.VIA.MOBILE.TITLE : IAM.AC.CHOOSE.OTHER_MODES.MOBILE.HEADING
  IAM.RELOGIN.VERIFY.VIA.EMAIL.TITLE : IAM.AC.CHOOSE.OTHER_MODES.EMAIL.HEADING
  
  #No account is associated with this mobile number.
  IAM.SIGNIN.ERROR.INVALID.MOBILE : IAM.NEW.RECOVERY.ERROR.INVALID.EMOBILE
  
  #You''re not allowed to accept the Invitation. You must be a super admin for the Organisation <b>{0}</b> to accept the invitation.
  IAM.ORG.INVITATION.ROLE.NOT.SUPPORT : IAM.ORG.MERGE.INVITATION.ROLE.NOT.SUPPORT
  
  #Either you didn''t allow this operation, or it got timed out. Please try again.
  IAM.WEBAUTHN.ERROR.ABORTERROR : IAM.WEBAUTHN.ERROR.NOTALLOWEDERROR
  
  #Mobile transactions limit exceeded for the day
  IAM.TRANSACTION.LIMIT.EXCEEDED : IAM.ERROR.CODE.AS108
  
  #This mobile has been marked spam.
  IAM.ERROR.CODE.SCREENNAME.AS101 : IAM.ERROR.CODE.AS101
  
  #Possible SPAM detected. Mobile transaction is temporarily blocked. Please contact support.
  IAM.SMS.BLOCKED.ANTISPAM : IAM.ERROR.CODE.AS111
  
  #Adding user with this domain is restricted by domain admin.
  IAM.ERROR.USER.EMAIL.RESTRICTED : IAM.ERROR.CODE.U130
  
  #Mobile transactions for your country is temporarily blocked because of SPAM attack.
  IAM.SMS.COUNTRY.BLOCKED : IAM.ERROR.CODE.AS106
  
  #Session expired. Please refresh your page and try again.
  IAM.TFA.BANNER.TOKEN.EXPIRED.REFRESH : IAM.ERROR.CODE.U136
  
  #Mobile Number
  IAM.MOBILE : IAM.NEW.SIGNIN.MOBILE
  IAM.MOBILE.NUMBER : IAM.NEW.SIGNIN.MOBILE
  
  #Please enter the password
  IAM.PASSWORD.ERROR.PASS_NOT_EMPTY : IAM.ERROR.ENTER.LOGINPASS
  
  #Please enter the question
  IAM.ERROR.ENTER.QUESTION : IAM.ERROR.ENTER.QUES
  
  #Password cannot be less than {0} characters
  IAM.ERROR.PASS.LENGTH : IAM.ERROR.PASS.LEN
  
  #Please read and accept the Terms of Service and Privacy Policy
  IAM.ACCOUNT.SIGNUP.POLICY.ERROR.TEXT : IAM.ERROR.TERMS.POLICY
  
  #Forgot Password?
  IAM.FORGOT.PASS : IAM.FORGOT.PASSWORD
  
  #Not useful
  IAM.NOT_USEFUL : IAM.NOT.USEFUL
  
  #Note
  IAM.NOTE.WARN : IAM.NOTE
  
  #Privacy Policy
  IAM.TOS.ANNOUNCEMENT.UPDATED.PRIVACY : IAM.PRIVACY
  
  #Sign in
  IAM.SIGNIN : IAM.SIGN_IN
  
  #Terms of Service
  IAM.TOS.ANNOUNCEMENT.UPDATED.TOS : IAM.SIGNUP.TERMS.OFSERVICE
  
  #Show
  IAM.ACTIVETOKEN.SHOWTEXT : IAM.PASSWORD.SHOW
  
  #Error while updating the group
  IAM.GROUP.ERROR.UPDATE.MESSAGE : IAM.GROUP.ERROR.UPDATE
  
  #Sign in using
  IAM.SIGNIN.USING : IAM.NEW.SIGNIN.FEDERATED.LOGIN.TITLE
  
  #Password cannot be more than {0} characters
  IAM.ERROR.PASSWORD.MAX.LENGTH : IAM.ERROR.PASSWORD.MAXLEN
  
  #Reset Password
  IAM.MSG.POPUP.PASSWORD.HEADING : IAM.ACCOUNT.RECOVEY.TITLE
  IAM.RESET.PASSWORD.TITLE : IAM.ACCOUNT.RECOVEY.TITLE
  
  #Security
  IAM.FOOTER.SECURITY : IAM.MENU.SECURITY
  
  #An account already exists for this mobile number.
  IAM.SIGNUP.ERROR.PHONENUMBER.EXISTS.PORTAL : IAM.ERROR.PHONENUMBER.MOBILE.ALREADY.EXISTS
  
  #Go Back
  IAM.GAPPS.GOBACK : IAM.AC.CONTACT.SUPPORT.GO_BACK
  
  #Thank you
  IAM.TPL.THANK.YOU : IAM.TPL.THANKS
  
  #Image verification
  IAM.TITLE.RANDOM : IAM.IMAGE.VERIFICATION
  
  #Account already confirmed
  IAM.CONFIRMATION.ERROR.ALREADY.CONFIRMED : IAM.EMAIL.ALREADYCONFIRM.TITLE
  
  #Access Denied
  IAM.DPA.ERROR.ACCESS.DENIED : IAM.NEW.SIGNIN.RESTRICT.SIGNIN.HEADER
  IAM.OAUTH.ACCESS.DENIED : IAM.NEW.SIGNIN.RESTRICT.SIGNIN.HEADER
  IAM.ACCESS.DENIED : IAM.NEW.SIGNIN.RESTRICT.SIGNIN.HEADER
  
  #Authtoken({0}) revoked successfully
  IAM.ACTIVETOKEN.REVOKE.SUCCESS.MESSAGE : IAM.ACTIVETOKEN.REVOKE.SUCCESS
  
  #Send Code
  IAM.TFA.BANNER.SEND.CODE : IAM.SEND.VERIFY
  
  #Password Verification
  IAM.NEW.SIGNIN.MFA.PASSWORD.HEADER : IAM.PASSWORD.VERIFICATION
  IAM.PASSWORD.VERIFICATION.HEAD : IAM.PASSWORD.VERIFICATION
  
  #Backup verification code
  IAM.BACKUP.VERIFICATION_CODE : IAM.BACKUP.VERIFICATION.CODE
  
  #Generate New Codes
  IAM.GENERATE.NEW.CODES : IAM.TFA.GENERATE.NEW
  IAM.TFA.GENERATE.NEW_CODES : IAM.TFA.GENERATE.NEW
 
  #Hide
  IAM.ACTIVETOKEN.HIDETEXT : IAM.PASSWORD.HIDE
  
  #Learn more
  IAM.LEARN.LINK : IAM.TFA.LEARN.MORE
  
  #Remind me later
  IAM.REVERIFY.DOMAIN.REVERIFY.REMIND : IAM.TFA.BANNER.REMIND.LATER
  IAM.USER.PROFILE.REVIEW.REMIND.LATER : IAM.TFA.BANNER.REMIND.LATER
  
  #Manage Sessions
  IAM.ANNOUNCEMENT.SESSIONREMINDER.MANAGESESSIONS : IAM.SESSION.MANAGEMENT.ANNOUNCEMENT.MANAGE.SESSION.ACTION
  IAM.SESSION_ALERT.ACTION.MANAGE : IAM.SESSION.MANAGEMENT.ANNOUNCEMENT.MANAGE.SESSION.ACTION
  
  #Account already exists
  IAM.GROUP.INVITATION.ACCOUNT.EXISTS.IN.ANOTHER.DC.HEADER : IAM.ACCOUNT.ALREADY.EXISTS
  
  #Verify mobile number
  IAM.PROFILE.PHONENUMBERS.VERIFY.HEADING : IAM.INVITAION.VERIFY.MOBILE
  
  #Please enter a valid mobile number
  IAM.PHONE.ENTER.VALID.MOBILE : IAM.PHONE.ENTER.VALID.MOBILE_NUMBER
  
  #Add Mobile Number
  IAM.ADD.PHONE.NUMBER : IAM.ADD.CONTACT.MOBILE
  
  #Add Email Address
  IAM.EMAIL.ADDRESS.ADD : IAM.ADD.CONTACT.EMAIL
  
  #Not you?
  IAM.NOT_YOU : IAM.NOT.YOU
  
  #Hi {0} !
  IAM.HI.EXCLAMATION : IAM.HI.USERNAME.EXCLAMATION
  
  #Scope does not exist.
  IAM.OAUTH.INVALID.SCOPE.DESC : IAM.OAUTH.INVALID.OPERATION.TYPE.DESC
  
  #Get Your Personal Information
  IAM.OAUTH.FHIRUSER.SCOPE.DESC : IAM.OAUTH.PROFILE.SCOPE.DESC
  
  #Confirm your password
  IAM.USER.EMAIL.ADD.CONFIRM.PASSWORD.PLACEHOLDER : IAM.OAUTH.VERIFY.MOBILEAPP
  
  #Blogs
  IAM.BLOGS : IAM.HEADER.BLOGS
  
  #Forums
  IAM.FORUMS : IAM.HEADER.FORUMS
  
  #$REBRAND_PARTNER_NAME Team
  IAM.NEW.TPL.ZOHO.TEAM : IAM.TPL.ZOHO.TEAM
  
  #This e-mail is generated from $REBRAND_PARTNER_NAME Accounts. If you think this is SPAM, please report to <a href : "mailto:{0}" style : "color:#0000ff;">{0}</a> for immediate action.
  IAM.TPL.SPAM.TEXT.CONFIG : IAM.TPL.SPAM.TEXT
  
  #Reset $REBRAND_PARTNER_NAME Account IP Restriction.
  IAM.NEW.EMAIL.IP.CHANGE.REQUEST : IAM.NEW.RESET.IP.MAIL.SUBJECT
  
  #www.$REBRAND_PARTNER_DOMAIN
  IAM.NEW.HOME.LINK.TEXT : IAM.HOME.LINK.TEXT
  
  #Smart Sign-in via OneAuth
  IAM.SMART.SIGNIN.TAB.TITLE : IAM.SMART.SIGNIN.TITLE
  
  #Google
  IAM.IDENTITY.PROVIDER.NAME.GOOGLE : IAM.GOOGLE
  
  #Generate Backup Codes
  IAM.TFA.BANNER.SUCCSES.BANNER.GENERATE.BACKUP.BUTTON : IAM.GENERATE.BACKUP.CODES
  
  #Preferred Number
  IAM.TFA.PREFERRED.NUMBER.TEXT : IAM.MFA.ANNOUN.SMS.PREF.LABEL
  
  #Primary Device
  IAM.MFA.PRIMARY.DEVICE : IAM.MFA.ANNOUN.ONEAUTH.PREF.LABEL
  
  #Invalid Mobile Number
  IAM.ERROR.INVALID.MOBILE.NUMBER : IAM.ERROR.CODE.PH105
  
  #Administrator approval pending
  IAM.SIGNIN.ERROR.USER.NOT.APPROVED.TITLE : IAM.CLIENT.SIGNUP.ADMIN.TITLE
  
  #Reset $REBRAND_PARTNER_NAME Account Password
  IAM.NEW.RESET.PASSWORD.MAIL.SUBJECT : IAM.NEW.EMAIL.PASSWORD.CHANGE.REQUEST