#This will used only in build script to generate proto files
#Generated multi files instead of generate single proto file to avoid memory issues while init single proto file.

### When adding new resource-group, following changes should be done in ``ant.properties``(Both On-Premise and On-Cloud).

# Include that in parallel_compile_contextpkg_context=existing_orders,{new_proto_group_name}_order
# Add new entries, refer 'accounts_proto_order'
# {new_proto_group_name}_order=compilesrc:{new_proto_group_name}protosrc
# {new_proto_group_name}protosrc_classpath=${proto_compile_classpath}
# {new_proto_group_name}protosrc_classes_dir=${proto_classes_dir}
# {new_proto_group_name}protosrc_compile_includes=${proto_source_dir}/{new_proto_file_name_1}.java ${proto_source_dir}/{new_proto_file_name_2}.java, ......

###
---
resource-groups:
  Accounts:
    resources:
        - Account
        - Register
 
#This is Temp resource used to bundle.        
#  AccountsTemp:
#    resources:
#        - Validate
#        - UserAppAccountDetails
#        - TokenDetails


  AppResource:
    resources:
        - App
        - Operation
        - DeploymentConfig
        - CacheCluster

  AgentResource:
    resources:
        - ZAID

  AccountsInternal:
    resources:
        - ServiceOrgType
        - ISCUserTicketUsage
        - InvitedUserDetails
        - OAuthTokenUsage
        - RoleAccessCheck
        - CacheDataStore
  OAuthResource:
    resources:
        - OAuthAppGroup
        - OAuthKeys
        - OAuthZID
        - AuthtoOAuth
        - AuthTokenDeletion
        - OAuthMobileAppService
        - OAuthMobileUserDevice
        - OAuthClientUsageInfo
        - OAuthProject

  SystemResource:
    resources:
        - Listener
        - Partner
        - ISDCode
        - TelesignLanguage
        - UniqueId
        - UniqueIdRange
        - UserAnnouncementStatus
        - DCLocation
        - ShortenURL
        - UserApp
        - MobileCount
        - UserExpiry
        - BreachedPassword
  AuditResource:
    resources:
        - AccountAudit
        - ResourceAudit
        - RegistrationAudit
        - AccountCloseAudit
        - AccountUpdateAudit
        - APIAudit
        - MailStatusQueue
        - SignInFailedAudit
        - WebSignInFailedAudit
        - OAuthAudit
        - MFAAudit
        - ZIDAudit
        - ZAIDSMSAudit
        - TFAAudit
        - MailClientAudit
        - MailClientAuditTemplate
        - AccountAuditTemplate
        - ResourceAuditTemplate
        - RegistrationAuditTemplate
        - AccountUpdateAuditTemplate
        - APIAuditTemplate
        - ZAIDSMSAuditTemplate
        - TFAAuditTemplate
        - MFAAuditTemplate
        - SignInFailedAuditTemplate
        - OAuthAuditTemplate
        - PrivacyCertificateAudit

docs-exclude-pattern: UniqueId|ISCTicket|OrgUPAuthToken|ISCUserTicketUsage

docs-root-resources: App,Account,OAuthAppGroup,OAuthZID,Operation,DeploymentConfig,CacheCluster,ZAID,ServiceOrgType,ISCUserTicketUsage,InvitedUserDetails,OAuthTokenUsage,RoleAccessCheck,OAuthKeys,AuthtoOAuth,AuthTokenDeletion,OAuthMobileAppService,Listener,Partner,ISDCode,TelesignLanguage,UniqueId,UniqueIdRange,UserAnnouncementStatus,DCLocation,ShortenURL,UserApp,MobileCount,UserExpiry,BreachedPassword,AccountAudit,ResourceAudit,RegistrationAudit,AccountCloseAudit,AccountUpdateAudit,APIAudit,MailStatusQueue,SignInFailedAudit,WebSignInFailedAudit,OAuthAudit,MFAAudit,ZIDAudit,ZAIDSMSAudit,TFAAudit,MailClientAudit,MailClientAuditTemplate,AccountAuditTemplate,ResourceAuditTemplate,RegistrationAuditTemplate,AccountUpdateAuditTemplate,APIAuditTemplate,ZAIDSMSAuditTemplate,TFAAuditTemplate,MFAAuditTemplate,SignInFailedAuditTemplate,OAuthAuditTemplate,OAuthMobileUserDevice,PrivacyCertificateAudit,OAuthProject

include-autoid-in-proto:
    OAuthRefreshToken:
        - oauth_refresh_token_auto_id

exclude-resources: Partner

