/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.x-dev
 * Generated at: 2024-06-28 09:25:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.v2.ui.unauth;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.zoho.accounts.internal.signin.DataHandler;
import com.zoho.accounts.AccountsConstants;
import com.adventnet.iam.xss.IAMEncoder;
import com.zoho.accounts.internal.util.ClientPortalUtil;
import java.util.Set;
import java.util.HashSet;
import com.zoho.accounts.internal.util.I18NUtil;
import com.adventnet.iam.Service;
import com.zoho.accounts.internal.util.StaticContentLoader;
import com.zoho.accounts.templateengine.util.HtmlResourceIncluder;
import com.zoho.accounts.AccountsConfiguration;
import com.adventnet.iam.Org;
import com.adventnet.iam.IAMStatusCode.StatusCode;
import com.adventnet.iam.IAMException.IAMErrorCode;
import com.zoho.iam.rest.metadata.ICRESTMetaData;
import com.adventnet.iam.security.SecurityRequestWrapper;
import com.adventnet.iam.security.ActionRule;
import org.json.JSONObject;
import com.adventnet.iam.internal.Util;
import com.adventnet.iam.IAMUtil;
import com.adventnet.iam.security.IAMSecurityException;
import com.zoho.iam.rest.ICRESTManager;
import com.zoho.iam.rest.representation.ICRESTRepresentation;
import java.util.logging.Level;
import java.util.logging.Logger;

public final class ui_002derror_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/v2/ui/unauth/../unauth/footer.jspf", Long.valueOf(1718999928000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(25);
    _jspx_imports_classes.add("com.adventnet.iam.Service");
    _jspx_imports_classes.add("com.adventnet.iam.IAMStatusCode.StatusCode");
    _jspx_imports_classes.add("com.adventnet.iam.security.IAMSecurityException");
    _jspx_imports_classes.add("com.zoho.iam.rest.representation.ICRESTRepresentation");
    _jspx_imports_classes.add("com.adventnet.iam.Org");
    _jspx_imports_classes.add("java.util.logging.Level");
    _jspx_imports_classes.add("java.util.HashSet");
    _jspx_imports_classes.add("org.json.JSONObject");
    _jspx_imports_classes.add("com.zoho.iam.rest.metadata.ICRESTMetaData");
    _jspx_imports_classes.add("com.adventnet.iam.IAMException.IAMErrorCode");
    _jspx_imports_classes.add("com.zoho.accounts.internal.util.I18NUtil");
    _jspx_imports_classes.add("com.zoho.iam.rest.ICRESTManager");
    _jspx_imports_classes.add("com.adventnet.iam.security.ActionRule");
    _jspx_imports_classes.add("com.zoho.accounts.internal.util.StaticContentLoader");
    _jspx_imports_classes.add("com.zoho.accounts.AccountsConstants");
    _jspx_imports_classes.add("java.util.Set");
    _jspx_imports_classes.add("com.adventnet.iam.security.SecurityRequestWrapper");
    _jspx_imports_classes.add("com.adventnet.iam.xss.IAMEncoder");
    _jspx_imports_classes.add("java.util.logging.Logger");
    _jspx_imports_classes.add("com.zoho.accounts.AccountsConfiguration");
    _jspx_imports_classes.add("com.zoho.accounts.internal.util.ClientPortalUtil");
    _jspx_imports_classes.add("com.zoho.accounts.templateengine.util.HtmlResourceIncluder");
    _jspx_imports_classes.add("com.zoho.accounts.internal.signin.DataHandler");
    _jspx_imports_classes.add("com.adventnet.iam.internal.Util");
    _jspx_imports_classes.add("com.adventnet.iam.IAMUtil");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    java.lang.Throwable exception = org.apache.jasper.runtime.JspRuntimeLibrary.getThrowable(request);
    if (exception != null) {
      response.setStatus(javax.servlet.http.HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
    }
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


	response.setContentType("text/html;charset=UTF-8"); //No I18N
	String errorTitle = I18NUtil.getMessage("IAM.ERRORJSP.ERROR.OCCURED.TITLE");//No I18N
	String errorDescryption = null;
	Set<String> serviceSet =new HashSet<String>();
	boolean showLogout = false;
	boolean hideHomeRedirection = false;
	StatusCode code = (StatusCode) request.getAttribute("statuscode") != null ? (StatusCode) request.getAttribute("statuscode") : StatusCode.GENERAL_ERROR;//No I18N
	switch (code) {
	case SAML_UNSUPPORTED_AUTHENTICATION: {
		errorTitle = Util.getI18NMsg(request, "IAM.SAML.ERROR.AUTHENTICATION.FAILED.TITLE");//No I18N
		errorDescryption = Util.getI18NMsg(request, "IAM.SAML.SP.ERROR.UNSUPPORTED.AUTH.RESPONSE.DESC");//No I18N
		break;
	}
	case INVALID_SAML_RESPONSE: {
		errorTitle = Util.getI18NMsg(request, "IAM.SAML.SP.ERROR.INVALID.RESPONSE.TITLE");//No I18N
		errorDescryption = Util.getI18NMsg(request, "IAM.SAML.SP.ERROR.INVALID.RESPONSE.DESC");//No I18N
		break;
	}
	case INVALID_SAML_STATUS_CODE: {
		errorTitle = Util.getI18NMsg(request, "IAM.SAML.SP.ERROR.INVALID.STATUSCODE.TITLE");//No I18N
		errorDescryption = Util.getI18NMsg(request, "IAM.SAML.SP.ERROR.INVALID.STATUSCODE.DESC");//No I18N
		break;
	}
	case SAML_RESPONDER_LOGIN_FAILED: {
		errorDescryption = Util.getI18NMsg(request, "IAM.SAML.SP.RESPONDER.LOGIN.FAILED.DESC");//No I18N
		break;
	}
	case SAML_REQUESTER_LOGIN_FAILED: {
		errorDescryption = Util.getI18NMsg(request, "IAM.SAML.SP.REQUESTER.LOGIN.FAILED.DESC");//No I18N
		break;
	}
	case SAML_NOT_CONFIGURED: {
		errorTitle = Util.getI18NMsg(request, "IAM.SAML.ERROR.NOT.CONFIGURED.TITLE");//No I18N
		errorDescryption = Util.getI18NMsg(request, "IAM.SAML.ERROR.NOT.CONFIGURED.DESC");//No I18N
		break;
	}
	case SAML_NOT_ENABLED: {
		errorTitle = Util.getI18NMsg(request, "IAM.SAML.ERROR.DISABLED.TITLE");//No I18N
		errorDescryption = Util.getI18NMsg(request, "IAM.SAML.ERROR.DISABLED.DESC");//No I18N
		break;
	}
	case SAML_SIGNATURE_FAILED: {
		errorTitle = Util.getI18NMsg(request, "IAM.SAML.SP.ERROR.SIGNATURE.FAILED.TITLE");//No I18N
		errorDescryption = Util.getI18NMsg(request, "IAM.SAML.SP.ERROR.SIGNATURE.FAILED.DESC");//No I18N
		break;
	}
	case SAML_CONDITIONS_FAILED: {
		errorTitle = Util.getI18NMsg(request, "IAM.SAML.ERROR.AUTHENTICATION.FAILED.TITLE");//No I18N
		errorDescryption = Util.getI18NMsg(request, "IAM.SAML.ERROR.AUTHENTICATION.FAILED.DESC");//No I18N
		break;
	}
	case INVALID_SAML_DESTINATION_ATTRIBUTE: {
		errorTitle = Util.getI18NMsg(request, "IAM.SAML.ERROR.INCORRECT.DESTINATION.TITLE");//No I18N
		errorDescryption = Util.getI18NMsg(request, "IAM.SAML.ERROR.INCORRECT.DESTINATION.DESC");//No I18N
		break;
	}
	case INVALID_SAML_SUBJECT_CONFIRMATION: {
		errorTitle = Util.getI18NMsg(request, "IAM.SAML.ERROR.INCORRECT.SUBJECT.CONFIRMATION.TITLE");//No I18N
		errorDescryption = Util.getI18NMsg(request, "IAM.SAML.ERROR.INCORRECT.SUBJECT.CONFIRMATION.DESC");//No I18N
		break;
	}
	case INVALID_SAML_EMAILID: {
		String email = String.valueOf(request.getAttribute("email"));
		errorTitle = Util.getI18NMsg(request, "IAM.ERROR.INVALID.EMAIL.TITLE");//No I18N
		errorDescryption = Util.getI18NMsg(request, "IAM.SAML.ERROR.INVALID.EMAIL.DESC", email);//No I18N
		break;
	}
	case SAML_AUTHDOMAIN_MISMATCH: {
		errorTitle = Util.getI18NMsg(request, "IAM.SAML.ERROR.AUTHENTICATION.FAILED.TITLE");//No I18N
		errorDescryption = Util.getI18NMsg(request, "IAM.SAML.ERROR.MISMATCH.AUTHDOMAIN.DESC");//No I18N
		break;
	}
	case SAML_EXCLUDED_USER: {
		errorTitle = Util.getI18NMsg(request, "IAM.SAML.ERROR.EXCLUDED.USER.TITLE");//No I18N
		errorDescryption = Util.getI18NMsg(request, "IAM.SAML.ERROR.EXCLUDED.USER.DESC");//No I18N
		break;
	}
	case SAML_NO_SUCH_USER: {
		Org org = (Org) request.getAttribute("org");
		String adminEmail = DataHandler.getInstance().getOrgContactSupportEmail(org);
		String email = String.valueOf(request.getAttribute("email"));
		errorTitle = Util.getI18NMsg(request, "IAM.SAML.ERROR.USER.NOT.EXIST.TITLE");//No I18N
		errorDescryption = Util.getI18NMsg(request, "IAM.SAML.ERROR.DISABLED.USER.PROVISIONING.DESC", email, IAMUtil.isValid(adminEmail) ? adminEmail :"");//No I18N
		break;
	}
	case SAML_USER_PROVISIONING_FAILED: {
		errorTitle = Util.getI18NMsg(request, "IAM.SAML.ERROR.FAILED.USER.PROVISIONING.TITLE");//No I18N
		errorDescryption = Util.getI18NMsg(request, "IAM.SAML.ERROR.FAILED.USER.PROVISIONING.DESC");//No I18N
		serviceSet= (Set<String>)request.getAttribute("failed_services");
		break;
	}
	case SAML_USER_LIMIT_EXCEEDED: {
		Org org = (Org) request.getAttribute("org");
		String adminEmail = org != null ? Util.USERAPI.getUserFromZUID(String.valueOf(org.getOrgContact())).getContactEmail() : "";
		errorTitle = Util.getI18NMsg(request, "IAM.SAML.ERROR.EXCEEDED.USER.LIMIT.TITLE");//No I18N
		errorDescryption = Util.getI18NMsg(request, "IAM.SAML.ERROR.EXCEEDED.USER.LIMIT.DESC", adminEmail);//No I18N
		break;
	}
	case SAML_ORG_DOMAIN_MISMATCH: {
		Org org = (Org) request.getAttribute("org");
		String adminEmail = org != null ? Util.USERAPI.getUserFromZUID(String.valueOf(org.getOrgContact())).getContactEmail() : "";
		errorTitle = Util.getI18NMsg(request, "IAM.SAML.ERROR.UNVERIFIED.ORG.DOMAIN.TITLE");//No I18N
		errorDescryption = Util.getI18NMsg(request, "IAM.SAML.ERROR.UNVERIFIED.ORG.DOMAIN.DESC", adminEmail);//No I18N
		break;
	}
	case SAML_ORG_DOMAIN_NOT_VERIFIED: {
		Org org = (Org) request.getAttribute("org");
		String adminEmail = org != null ? Util.USERAPI.getUserFromZUID(String.valueOf(org.getOrgContact())).getContactEmail() : "";
		errorTitle = Util.getI18NMsg(request, "IAM.SAML.ERROR.UNVERIFIED.ORG.DOMAIN.TITLE");//No I18N
		errorDescryption = Util.getI18NMsg(request, "IAM.SAML.ERROR.UNVERIFIED.ORG.DOMAIN.DESC", adminEmail);//No I18N
		break;
	}
	case SAML_PARTNER_ORG_MISMATCH: {
		errorTitle = Util.getI18NMsg(request, "IAM.SAML.ERROR.INVALID.AUTHENTICATION.TITLE");//No I18N
		errorDescryption = Util.getI18NMsg(request, "IAM.SAML.ERROR.INVALID.AUTHENTICATION.DESC");//No I18N
		break;
	}
	case INVALID_SAML_USER: {
		errorDescryption = Util.getI18NMsg(request, "IAM.SAML.ERROR.INVALID.USER.DESC");//No I18N
		break;
	}
	case SAML_GENERAL_ERROR: {
		errorDescryption = Util.getI18NMsg(request, "IAM.SAML.ERROR.GENERAL.DESC");//No I18N
		break;
	}
	case SAML_NO_SUCH_ORG: {
		errorTitle = Util.getI18NMsg(request, "IAM.ORG.ERROR.NOT.EXIST.TITLE");//No I18N
		errorDescryption = Util.getI18NMsg(request, "IAM.ORG.ERROR.NOT.EXIST.DESC");//No I18N
		break;
	}
	case INVALID_SAML_LOGOUT_REQUEST: {
		errorTitle = Util.getI18NMsg(request, "IAM.SAML.ERROR.SIGNOUT.TITLE");//No I18N
		errorDescryption = Util.getI18NMsg(request, "IAM.SAML.IDP.ERROR.SIGNOUT.DESC");//No I18N
		break;
	}
	case USER_NOT_ACTIVE: {
		errorDescryption = Util.getI18NMsg(request, "IAM.SIGNIN.ERROR.USER.NOT.ACTIVE",Util.getSupportEmailId());//No I18N
		break;
	}
	case USER_MARKED_AS_SPAM: {
		errorTitle = Util.getI18NMsg(request, "IAM.ERRORJSP.ERROR.OCCURED.TITLE");//No I18N
		errorDescryption = Util.getI18NMsg(request, "IAM.SIGNIN.ERROR.USER.SPAM",AccountsConfiguration.ANTI_SPAM_SUPPORT_EMAILID.toStringValue());//No I18N
		break;
	}
	case USER_NOT_ACTIVE_IN_SERVICE: {
		Service service = Util.getServiceObject(request.getParameter("servicename"));
		String serviceName = service != null ? service.getDisplayName() : "" ;
		errorDescryption = Util.getI18NMsg(request, "IAM.SIGNIN.ERROR.USER.NOT.ACTIVE.IN.SERVICE", serviceName, Util.getSupportEmailId());//No I18N
		break;
	}
	case DAILY_SIGNIN_LIMIT_REACHED: {
		errorDescryption = Util.getI18NMsg(request, "IAM.SIGNIN.ERROR.USER.DAILY.SIGNIN.LIMIT.EXCEEDED",AccountsConfiguration.getConfiguration("iam.login.limit.learnwhy.link", "https://help.zoho.com/portal/en/kb/accounts/troubleshooting/sign-in/articles/troubleshoot-sign-in-related-issues#What_is_a_daily_sign-in_limit"));//No I18N
		break;
	}
	case UNAUTHORIZED_ORG_NETWORK_ACCESS: {
		errorDescryption = Util.getI18NMsg(request, "IAM.SIGNIN.ERROR.ORG.NETWORK.BLOCKED");//No I18N
		break;
	}
	case RESTRICT_SIGNIN_ENABLED: {
		errorDescryption = Util.getI18NMsg(request, "IAM.SIGNIN.ERROR.RESTRICT.SIGNIN.ENABLED");//No I18N
		break;
	}
	case GENERAL_ERROR: {
		errorDescryption = Util.getI18NMsg(request, "IAM.ERROR.GENERAL.REQUEST.PROCESSING");//No I18N
		break;
	}
	case INVALID_AUTHORIZE_REQUEST: {
		errorTitle = I18NUtil.getMessage("IAM.AUTHORIZE.PAGE.SUSPICIOUS.REQUEST.TITLE");
		errorDescryption = I18NUtil.getMessage("IAM.AUTHORIZE.PAGE.SUSPICIOUS.REQUEST.DESCRIPTION");
		break;
	}
	case LINKED_ACCOUNT_THROTTLE_EXCEEDED: {
		errorTitle = I18NUtil.getMessage("IAM.LINKED.ACCOUNTS.THROTLLE.EXCEEDED.TITLE");
		String provider = (String)request.getAttribute("provider");
		provider = provider.charAt(0) + provider.substring(1).toLowerCase();
		errorDescryption = I18NUtil.getMessage("IAM.LINKED.ACCOUNTS.THROTLLE.EXCEEDED.DESCRIPTION", provider);
		break;
	}
	case OAUTH_ACCESS_LIMIT_EXCEEDED: {
		errorTitle = I18NUtil.getMessage("IAM.NEW.SIGNIN.RESTRICT.SIGNIN.HEADER");
		errorDescryption = I18NUtil.getMessage("IAM.OAUTH.ACCESS.DENIED.UI.DESCRIPTION");
		break;
	}
	case URL_RULE_NOT_CONFIGURED : 
		errorTitle = I18NUtil.getMessage("IAM.ERROR.JSP.URL_RULE_NOT_CONFIGURED.TITLE");
		errorDescryption = I18NUtil.getMessage("IAM.ERROR.JSP.URL_RULE_NOT_CONFIGURED.DESC");
		break;	
	case INVALID_SORG_INVITATION: {
		errorDescryption = I18NUtil.getMessage("IAM.SORGINVITATION.INVALID.ENDPOINT.URL");//No I18N
		break;
	}
	case USER_NOT_CONFIRMED: {
		errorDescryption = I18NUtil.getMessage("IAM.GROUP.CREATE.ERROR.UNCONFIRMED.USER");
		break;
	}
	case USER_PENDING_INVITATION_NOT_EXISTS: {
		errorDescryption = I18NUtil.getMessage("IAM.SORGINVITATION.NO.PENDING.INVITATIONS");
		break;
	}
	case UNTRUSTED_DOMAIN:{
		errorTitle = I18NUtil.getMessage("IAM.UNTRUSTED.DOMAIN.TITLE");
		errorDescryption = I18NUtil.getMessage(DataHandler.getInstance().isClientPortal() ? "IAM.PORTAL.UNTRUSTED.DOMAIN.DESC" : "IAM.UNTRUSTED.DOMAIN.DESC");
		break;	
	}
	case UNTRUSTED_REDIRECT_DOMAIN: {
		errorTitle = I18NUtil.getMessage("IAM.UNTRUSTED.DOMAIN.TITLE");
		errorDescryption = I18NUtil.getMessage("IAM.PORTAL.UNTRUSTED.REDIRECT.DOMAIN");
		break;
	}
	case UNAPPROVED_USERS_LIMIT_EXCEEDED:{
		String adminEmail = String.valueOf(request.getAttribute("admin_email"));
		errorTitle = I18NUtil.getMessage("IAM.SIGNIN.ERROR.UNAPPROVED.USERS.LIMIT.EXCEEDED.TITLE");
		errorDescryption = I18NUtil.getMessage("IAM.SIGNIN.ERROR.UNAPPROVED.USERS.LIMIT.EXCEEDED", Util.isValid(adminEmail)?adminEmail:"admin");
		break;
	}
	case USER_NOT_APPROVED: {
		String adminEmail = String.valueOf(request.getAttribute("admin_email"));
		errorTitle = I18NUtil.getMessage("IAM.CLIENT.SIGNUP.ADMIN.TITLE");
		errorDescryption = I18NUtil.getMessage("IAM.SIGNIN.ERROR.USER.NOT.APPROVED", Util.isValid(adminEmail)?adminEmail:"admin");
		break;
	}
	case USER_SIGNIN_MODE_NOT_ALLOWED: {
		String adminEmail = String.valueOf(request.getAttribute("admin_email"));
		errorTitle = I18NUtil.getMessage("IAM.REAUTH.ERROR.MODE.NOT.ALLOWED.TITLE");
		errorDescryption = I18NUtil.getMessage("IAM.AUTH.ERROR.MODE.NOT.ALLOWED.CONTACT", IAMUtil.isValid(adminEmail) ? adminEmail : "admin");
		break;
	}
	case MDM_TOKEN_BLOCKED: {
		errorTitle = I18NUtil.getMessage("IAM.ERROR.ACCESS.NOT.ALLOWED");
		errorDescryption = I18NUtil.getMessage("IAM.MDM.ERROR."+request.getAttribute("code"));
		showLogout = true;
		hideHomeRedirection = true;
		break;
	}
	case CONDITIONAL_ACCESS_BLOCK: {
		errorTitle = I18NUtil.getMessage("IAM.ERROR.ACCESS.NOT.ALLOWED");
		errorDescryption = I18NUtil.getMessage("IAM.CONDITIONAL.ACCESS.ERROR."+request.getAttribute("code"));
		showLogout = true;
		hideHomeRedirection = true;
		break;
	}
	case INACTIVE_PORTAL: {
		errorTitle = I18NUtil.getMessage("IAM.PORTAL.INACTIVE.TITLE");
		errorDescryption = I18NUtil.getMessage("IAM.PORTAL.INACTIVE.DESC");
		break;
	}
	case INVALID_PORTAL: {
		errorTitle = I18NUtil.getMessage("IAM.PORTAL.NOT.EXIST.TITLE");
		errorDescryption = I18NUtil.getMessage("IAM.PORTAL.NOT.EXIST.DESC");
		break;
	}
	case JWT_MAX_USER_LIMIT_REACHED_IN_PORTAL: {
		String adminEmail = String.valueOf(request.getAttribute("admin_email"));
		errorTitle = I18NUtil.getMessage("IAM.JWT.SIGNIN.ERROR.TITLE");
		errorDescryption = I18NUtil.getMessage("IAM.JWT.SIGNIN.ERROR.DESC", adminEmail);
		break;
	}
	case USER_NOT_ALLOWED_IP: {
   		request.getRequestDispatcher("/v2/ui/unauth/ip_restriction.jsp").forward(request, response); //No I18N
   		return;
	}
	default: {
		errorDescryption = code.getMessage();
		break;
	}
	}


	if(!serviceSet.isEmpty()	&&	code==StatusCode.SAML_USER_PROVISIONING_FAILED) 	
	{

      out.write("<html>\n");
      out.write("		<head>\n");
      out.write("			<title>");
      out.print( Util.getI18NMsg(request,"IAM.ACCOUNT.CREATION.BLOCKED"));
      out.write("</title>\n");
      out.write("			<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"/>\n");
      out.write("			<meta charset=\"UTF-8\" />\n");
      out.write("			<meta name=\"viewport\"content=\"width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=no\" />\n");
      out.write("			");
      out.print( HtmlResourceIncluder.addResource("/v2/components/css/zohoPuvi.css") );
      out.write("<style type=\"text/css\">\n");
      out.write("			\n");
      out.write("\n");
      out.write("				\n");
      out.write("				body \n");
      out.write("				{\n");
      out.write("				  height: auto;\n");
      out.write("				  width: 100%;\n");
      out.write("				  background-color: rgb(252 252 252);\n");
      out.write("				  margin: 0px;\n");
      out.write("				}\n");
      out.write("\n");
      out.write("				body .zohologo \n");
      out.write("				{\n");
      out.write("				    display: block;\n");
      out.write("				    height: 40px;\n");
      out.write("				    width: auto;\n");
      out.write("				    margin: auto;\n");
      out.write("				    margin-bottom: 20px;\n");
      out.write("				    margin-top: 100px;\n");
      out.write("				    background: url(\"");
      out.print(StaticContentLoader.getStaticFilePath("/v2/components/images/newZoho_logo.svg"));
      out.write("\") no-repeat transparent;\n");
      out.write("				    background-size: 100% auto;\n");
      out.write("				    background-position: center;\n");
      out.write("				}\n");
      out.write("\n");
      out.write("				body .info_block\n");
      out.write("				{\n");
      out.write("				    z-index: 4;\n");
      out.write("				    border-radius: 20px;\n");
      out.write("				    position: fixed;\n");
      out.write("				    left: 0px;\n");
      out.write("				    right: 0px;\n");
      out.write("				    top: 23%;\n");
      out.write("				    margin: auto;\n");
      out.write("				    height: auto;\n");
      out.write("				    width: 800px;\n");
      out.write("				    background: #fff;\n");
      out.write("				    outline: none;\n");
      out.write("				    transition: transform 0.2s ease-in-out;\n");
      out.write("				    transform: translateY(-50px);\n");
      out.write("				    padding: 30px;\n");
      out.write("				    padding-top: 20px;\n");
      out.write("				    overflow: hidden;\n");
      out.write("				    border-radius: 30px;\n");
      out.write("				}\n");
      out.write("\n");
      out.write("				.reject_icon \n");
      out.write("				{\n");
      out.write("				    width: 40px;\n");
      out.write("				    height: 40px;\n");
      out.write("				    border-radius: 50%;\n");
      out.write("				    overflow: hidden;\n");
      out.write("				    font-size: 44px;\n");
      out.write("				    margin: auto;\n");
      out.write("				    position: relative;\n");
      out.write("				    color: #939393;\n");
      out.write("				    margin-top: 12px;\n");
      out.write("				    font-weight: 600;\n");
      out.write("				    background: #16C188;\n");
      out.write("				    background: #dd5757;\n");
      out.write("				}\n");
      out.write("\n");
      out.write("\n");
      out.write("				.reject_icon:before \n");
      out.write("				{\n");
      out.write("				    display: block;\n");
      out.write("				    content: \"\";\n");
      out.write("				    height: 18px;\n");
      out.write("				    width: 3px;\n");
      out.write("				    background-color: #fff;\n");
      out.write("				    margin: auto;\n");
      out.write("				    border-radius: 1px;\n");
      out.write("				    transform: rotate(-45deg);\n");
      out.write("				    position: absolute;\n");
      out.write("				    top: 11px;\n");
      out.write("				    right: 0px;\n");
      out.write("				    left: 0px;\n");
      out.write("				    z-index: 1;\n");
      out.write("				}\n");
      out.write("\n");
      out.write("				.inner_circle \n");
      out.write("				{\n");
      out.write("				    display: inline-block;\n");
      out.write("				    width: 40px;\n");
      out.write("				    height: 40px;\n");
      out.write("				    position: relative;\n");
      out.write("				    top: -3px;\n");
      out.write("				    left: -3px;\n");
      out.write("				    background: #F66363;\n");
      out.write("				    border-radius: 50%;\n");
      out.write("				}\n");
      out.write("\n");
      out.write("\n");
      out.write("				.reject_icon:after \n");
      out.write("				{\n");
      out.write("				    display: block;\n");
      out.write("				    content: \"\";\n");
      out.write("				    height: 18px;\n");
      out.write("				    width: 3px;\n");
      out.write("				    border-radius: 1px;\n");
      out.write("				    background-color: #fff;\n");
      out.write("				    position: absolute;\n");
      out.write("				    margin: auto;\n");
      out.write("				    top: 11px;\n");
      out.write("				    transform: rotate(45deg);\n");
      out.write("				    right: 0px;\n");
      out.write("				    left: 0px;\n");
      out.write("				}\n");
      out.write("\n");
      out.write("				.grn_text \n");
      out.write("				{\n");
      out.write("					font: normal normal 600 24px/19px Zoho Puvi;\n");
      out.write("    				text-align: center;\n");
      out.write("				    color: #000000;\n");
      out.write("				    font-weight: 500;\n");
      out.write("				    font-size: 18px;\n");
      out.write("				    margin-top: 18px;\n");
      out.write("				    font-weight: 600;\n");
      out.write("				}\n");
      out.write("\n");
      out.write("				 .defin_text \n");
      out.write("				 {\n");
      out.write("				 	font: normal normal normal 16px/24px Zoho Puvi;\n");
      out.write("				    text-align: center;\n");
      out.write("				    margin-top: 10px;\n");
      out.write("				    font-size: 15px;\n");
      out.write("				    line-height: 20px;\n");
      out.write("				}\n");
      out.write("\n");
      out.write("\n");
      out.write("				.Service_space\n");
      out.write("				{\n");
      out.write("					margin-top: 30px\n");
      out.write("\n");
      out.write("				}\n");
      out.write("				.service_box\n");
      out.write("				{\n");
      out.write("					width: 550px;\n");
      out.write("				    height: 55px;\n");
      out.write("				    background: #FFFFFF 0% 0% no-repeat padding-box;\n");
      out.write("				    border: 1px solid #FFB7B7;\n");
      out.write("				    border-radius: 6px;\n");
      out.write("				    opacity: 1;\n");
      out.write("				    padding: 28px 20px 16px 20px;\n");
      out.write("				    position: relative;\n");
      out.write("				    margin: auto;\n");
      out.write("				    margin-top: 30px;\n");
      out.write("				}\n");
      out.write("\n");
      out.write("				.info_text\n");
      out.write("				{\n");
      out.write("					width: 550px;\n");
      out.write("				    height: 55px;\n");
      out.write("				    text-align: left;\n");
      out.write("				    letter-spacing: 0px;\n");
      out.write("				    color: #000000;\n");
      out.write("				    opacity: 0.8;\n");
      out.write("				    font-size: 14px;\n");
      out.write("				}\n");
      out.write("\n");
      out.write("				.service_info\n");
      out.write("				{\n");
      out.write("					display: inline-flex;\n");
      out.write("				    justify-content: space-around;\n");
      out.write("				    box-sizing: border-box;\n");
      out.write("				    max-width: 100%;\n");
      out.write("				    flex-wrap: nowrap;\n");
      out.write("				    width: 134px;\n");
      out.write("				    height: 36px;\n");
      out.write("				    background: transparent linear-gradient(90deg, #FFEDED 0%, #FFFFFF 100%) 0% 0% no-repeat padding-box;\n");
      out.write("				    border: 1px solid #FFB7B7;\n");
      out.write("				    border-radius: 46px;\n");
      out.write("				    opacity: 1;\n");
      out.write("				    position: absolute;\n");
      out.write("				    top: -18px;\n");
      out.write("				}\n");
      out.write("\n");
      out.write("				.service_name\n");
      out.write("				{\n");
      out.write("					font: normal normal medium 14px/24px Zoho Puvi;\n");
      out.write("				    letter-spacing: 0px;\n");
      out.write("				    color: #000000;\n");
      out.write("				    opacity: 1;\n");
      out.write("				    line-height: 2;\n");
      out.write("				    display: inline-block;\n");
      out.write("				}\n");
      out.write("\n");
      out.write("				.footer_warn\n");
      out.write("				{\n");
      out.write("					text-align: center;\n");
      out.write("				    margin-top: 20px;\n");
      out.write("				    font: normal normal normal 14px/20px Zoho Puvi;\n");
      out.write("				    letter-spacing: 0px;\n");
      out.write("				    color: #000000;\n");
      out.write("				    opacity: 0.7;\n");
      out.write("				}\n");
      out.write("\n");
      out.write("				.service_icon\n");
      out.write("				{\n");
      out.write("					display: inline-block;\n");
      out.write("    				font-size: 16px;\n");
      out.write("					border-radius: 50%;\n");
      out.write("				    height: 5px;\n");
      out.write("				    width: 5px;\n");
      out.write("				    box-sizing: border-box;\n");
      out.write("				    line-height: 20px;\n");
      out.write("				    background: #FF8181 0% 0% no-repeat padding-box;\n");
      out.write("				    opacity: 1;\n");
      out.write("				    margin-top: 14px;\n");
      out.write("				    margin-left: -3px;\n");
      out.write("				}\n");
      out.write("			\n");
      out.write("				.service_icon:after \n");
      out.write("				{\n");
      out.write("    				content: \"\";\n");
      out.write("				    width: 24px;\n");
      out.write("				    height: 24px;\n");
      out.write("				    margin-top: -9px;\n");
      out.write("				    display: inline-block;\n");
      out.write("				    background: url(ProductLogo-24.png) no-repeat transparent 0px -1595px;\n");
      out.write("				    background-size: 100% auto;\n");
      out.write("				    margin-left: 9px;\n");
      out.write("				    transform: scale(0.83);\n");
      out.write("				}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("				.icon_assist:after,.icon_zohoassist:after{background-position: 0px 0px;background-size: 24px auto;}\n");
      out.write("				.icon_zohobooks:after{background-position:0px -29px;background-size: 24px auto;}\n");
      out.write("				.icon_zohobugtracker:after,.icon_bugtracker:after{background-position:0px -58px;background-size: 24px auto;}\n");
      out.write("				.icon_campaigns:after,.icon_zohocampaigns:after{background-position:0px -87px;background-size: 24px auto;}\n");
      out.write("				.icon_zohoconnect:after,.icon_connect:after,.icon_zohopulse:after{background-position:0px -116px;background-size: 24px auto;}\n");
      out.write("				.icon_zohocontactmanager:after,.icon_contactmanager:after{background-position:0px -145px;background-size: 24px auto;}\n");
      out.write("				.icon_zohocreator:after,.icon_creator:after{background-position:0px -174px;background-size: 24px auto;}\n");
      out.write("				.icon_zohocrm:after,.icon_crm:after{background-position:0px -203px;background-size: 24px auto;}\n");
      out.write("				.icon_zohodocssync:after,.icon_docs:after{background-position:0px -232px;background-size: 24px auto;}\n");
      out.write("				.icon_zohoinvoice:after,.icon_invoice:after{background-position:0px -261px;background-size: 24px auto;}\n");
      out.write("				.icon_zohomail:after,.icon_mail:after,.icon_virtualoffice:after{background-position:0px -290px;background-size: 24px auto;}\n");
      out.write("				.icon_zohomeetingoutlookplugin:after,.icon_meeting:after,.icon_zohomeeting:after{background-position:0px -319px;background-size: 24px auto;}\n");
      out.write("				.icon_zohopeople:after,.icon_people:after{background-position:0px -348px;background-size: 24px auto;}\n");
      out.write("				.icon_zohoprojects:after,.icon_projects:after{background-position:0px -377px;background-size: 24px auto;}\n");
      out.write("				.icon_recruit:after{background-position:0px -406px;background-size: 24px auto;}\n");
      out.write("				.icon_zohoanalytics:after,.icon_analytics:after{background-position:0px -435px;background-size: 24px auto;}\n");
      out.write("				.icon_zohosalesiq:after,.icon_salesiq:after,.icon_livedesk:after{background-position:0px -464px;background-size: 24px auto;}\n");
      out.write("				.icon_zohosheet:after,.icon_sheet:after{background-position:0px -493px;background-size: 24px auto;}\n");
      out.write("				.icon_show:after,.icon_zohoshow:after{background-position:0px -522px;background-size: 24px auto;}\n");
      out.write("				.icon_site24x7:after{background-position:0px -551px;background-size: 24px auto;}\n");
      out.write("				.icon_sites:after,.icon_samplemerchandise:after{background-position:0px -580px;background-size: 24px auto;}\n");
      out.write("				.icon_zohosocial:after{background-position:0px -609px;background-size: 24px auto;}\n");
      out.write("				.icon_zohosubscriptions:after,.icon_subscriptionmanagement-zoho:after{background-position:0px -638px;background-size: 24px auto;}\n");
      out.write("				.icon_zohodesk:after,.icon_desk:after{background-position:0px -667px;background-size: 24px auto;}\n");
      out.write("				.icon_onlinesurvey:after,.icon_zohosurvey:after{background-position:0px -696px;background-size: 24px auto;}\n");
      out.write("				.icon_zohovault:after,.icon_vault:after{background-position:0px -725px;background-size: 24px auto;}\n");
      out.write("				.icon_writer:after,.icon_zohowriter:after{background-position:0px -754px;background-size: 24px auto;}\n");
      out.write("				.icon_zohoexpense:after{background-position:0px -783px;background-size: 24px auto;}\n");
      out.write("				.icon_zohoshowtime:after,.icon_showtime:after,.icon_viewershowtime:after,.icon_viewer:after{background-position:0px -812px;background-size: 24px auto;}\n");
      out.write("				.icon_zohocalendar:after,.icon_calendar:after{background-position:0px -841px;background-size: 24px auto;}\n");
      out.write("				.icon_zohoforms:after{background-position:0px -870px;background-size: 24px auto;}\n");
      out.write("				.icon_wiki:after,.icon_zohowiki:after{background-position:0px -899px;background-size: 24px auto;}\n");
      out.write("				.icon_zohomotivator:after{background-position:0px -928px;background-size: 24px auto;}\n");
      out.write("				.icon_zohochat:after,.icon_cliq:after{background-position:0px -957px;background-size: 24px auto;}\n");
      out.write("				.icon_zohofour:after{background-position:0px -986px;background-size: 24px auto;}\n");
      out.write("				.icon_zohoinventory:after,.icon_inventory:after{background-position:0px -1015px;background-size: 24px auto;}\n");
      out.write("				.icon_zohoappcreator:after,.icon_zohomcreator:after{background-position:0px -1044px;background-size: 24px auto;}\n");
      out.write("				.icon_salesinbox:after{background-position:0px -1073px;background-size: 24px auto;}\n");
      out.write("				.icon_zohomdm:after,.icon_mobiledevicemanagement:after,.icon_mdmondemand:after{background-position:0px -1102px;background-size: 24px auto;}\n");
      out.write("				.icon_zohocheckout:after{background-position:0px -1131px;background-size: 24px auto;}\n");
      out.write("				.icon_zohosign:after{background-position:0px -1160px;background-size: 24px auto;}\n");
      out.write("				.icon_zohosprints:after,.icon_sprints:after{background-position:0px -1189px;background-size: 24px auto;}\n");
      out.write("				.icon_zohonotebook:after,.icon_notebook:after{background-position:0px -1218px;background-size: 24px auto;}\n");
      out.write("				.icon_pagesense:after{background-position:0px -1247px;background-size: 24px auto;}\n");
      out.write("				.icon_zohoflow:after{background-position:0px -1276px;background-size: 24px auto;}\n");
      out.write("				.icon_zohobackstage:after{background-position:0px -1305px;background-size: 24px auto;}\n");
      out.write("				.icon_zohoteamdrive:after,.icon_teamdrive:after,.icon_workdrive:after,.icon_workdrivesync:after{background-position:0px -1334px;background-size: 24px auto;}\n");
      out.write("				.icon_zohocommerce:after,.icon_zohomerchandise:after{background-position:0px -1363px;background-size: 24px auto;}\n");
      out.write("				.icon_orchestly:after{background-position:0px -1392px;background-size: 24px auto;}\n");
      out.write("				.icon_zohoworkerly:after{background-position:0px -1421px;background-size: 24px auto;}\n");
      out.write("				.icon_zohoofficeintegrator:after,.icon_officeapi:after{background-position:0px -1450px;background-size: 24px auto;}\n");
      out.write("				.icon_zohomarketinghub:after{background-position:0px -1479px;background-size: 24px auto;}\n");
      out.write("				.icon_zohopayroll:after{background-position:0px -1508px;background-size: 24px auto;}\n");
      out.write("				.icon_zohoink:after{background-position:0px -1537px;background-size: 24px auto;}\n");
      out.write("				.icon_zohobookings:after{background-position:0px -1566px;background-size: 24px auto;}\n");
      out.write("				.icon_zohoone:after{background-position:0px -1624px;background-size: 24px auto;}\n");
      out.write("				.icon_bigin:after,.icon_zohobigin:after{background-position:0px -1653px;background-size: 24px auto;}\n");
      out.write("				.icon_crmplus:after{background-position:0px -1682px;background-size: 24px auto;}\n");
      out.write("				.icon_zohosd:after{background-position:0px -1711px;background-size: 24px auto;}\n");
      out.write("				.icon_zoholearn:after{background-position:0px -1740px;background-size: 24px auto;}\n");
      out.write("				.icon_zohofsm:after{background-position:0px -1769px;background-size: 24px auto;}\n");
      out.write("				.icon_zohodirectory:after{background-position:0px -1798px;background-size: 24px auto;}\n");
      out.write("				.icon_zohodeluge:after{background-position:0px -1827px;background-size: 24px auto;}\n");
      out.write("				.icon_remotely:after{background-position:0px -1856px;background-size: 24px auto;}\n");
      out.write("				.icon_zoholens:after{background-position:0px -1886px;background-size: 24px auto;}\n");
      out.write("				.icon_workplace:after{background-position:0px -1915px;background-size: 24px auto;}\n");
      out.write("				.icon_transmail:after{background-position:0px -1943px;background-size: 24px auto;}\n");
      out.write("				.icon_zohofinanceplus:after{background-position:0px -1972px;background-size: 24px auto;}\n");
      out.write("				.icon_it-management:after{background-position:0px -2001px;background-size: 24px auto;}\n");
      out.write("				.icon_mailapps:after{background-position:0px -2031px;background-size: 24px auto;}\n");
      out.write("				.icon_peopleplus:after{background-position:0px -2060px;background-size: 24px auto;}\n");
      out.write("				.icon_zohomarketplace:after{background-position:0px -2088px;background-size: 24px auto;}\n");
      out.write("				.icon_inventorystocktracker:after{background-position:0px -2118px;background-size: 24px auto;}\n");
      out.write("				.icon_oneauth:after,.icon_oneauth2\\.0:after{background: url(../images/ProductLogo-24-2x.png) no-repeat transparent 0px -4469px/50px auto;border-radius: 50%;width: 50px;height: 50px;margin: 0px;}\n");
      out.write("				.icon_zohoshifts:after{background-position: 0px -2175px;background-size: 24px auto;}\n");
      out.write("				.icon_zohocatalyst:after{background-position: 0px -2203px;background-size: 24px auto;}\n");
      out.write("				.hide\n");
      out.write("				{\n");
      out.write("					display: none;\n");
      out.write("				}\n");
      out.write("				\n");
      out.write("				@media only screen and (max-width: 435px) \n");
      out.write("				{\n");
      out.write("					body .info_block\n");
      out.write("					{\n");
      out.write("						width: 80%;\n");
      out.write("					}\n");
      out.write("					.info_text\n");
      out.write("					{\n");
      out.write("						width: auto;\n");
      out.write("    					height: auto;\n");
      out.write("					}\n");
      out.write("					.service_box\n");
      out.write("					{\n");
      out.write("   	 					width: auto;\n");
      out.write("    					height: auto;\n");
      out.write("					}\n");
      out.write("				}\n");
      out.write("			</style>\n");
      out.write("		</head>\n");
      out.write("		<body>\n");
      out.write("			\n");
      out.write("		<div class=\"info_block\" id=\"info_block\">\n");
      out.write("			<div class=\"reject_icon\"><span class=\"inner_circle\"></span></div>\n");
      out.write("			<div class=\"content_space\">\n");
      out.write("				<div class=\"grn_text\" id=\"result_content\">");
      out.print( Util.getI18NMsg(request,"IAM.ADMIN.ACTION.REQUIRED"));
      out.write("</div>\n");
      out.write("				<div class=\"defin_text\">");
      out.print( Util.getI18NMsg(request,"IAM.ADMIN.ACTION.REQUIRED.DESCRIPTION"));
      out.write("</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"Service_space\">\n");
      out.write("			");

				for(String service:serviceSet)
				{
					Org org =(Org) request.getAttribute("org");
					String orgContact=Util.USERAPI.getUserFromZUID(String.valueOf(org.getOrgContact())).getContactEmail();
					String icon="icon_"+service.toLowerCase().replaceAll("\\s", ""); 	//No I18N
			
      out.write("<div class=\"service_box\">\n");
      out.write("						<div class=\"service_info ");
      out.print(icon);
      out.write("\" id=\"recovery_user_info\" onclick=\"change_user()\">\n");
      out.write("				            <span class=\"service_icon\"></span>\n");
      out.write("				            <span class=\"service_name\">");
      out.print(service);
      out.write("</span>\n");
      out.write("			           	</div>\n");
      out.write("			           	<div class=\"info_text\">\n");
      out.write("			           		");
      out.print( Util.getI18NMsg(request,"IAM.SAML.SERVICE.LICENSE.NOTAVAIBLE.WARNING",orgContact));
      out.write("</div>\n");
      out.write("		\n");
      out.write("					</div>	\n");
      out.write("			");

				}
			
      out.write("</div>\n");
      out.write("\n");
      out.write("			<div class=\"footer_warn\">");
      out.print( Util.getI18NMsg(request,"IAM.SAML.ADMIN.ACTION.FOOTTER"));
      out.write("</div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("	   	<div class=\"zohologo\"></div>\n");
      out.write("		</body>\n");
      out.write("	</html>\n");
 
		
	}
	else
	{

      out.write("<html>\n");
      out.write("		<head>\n");
      out.write("		<title>");
      out.print( Util.getI18NMsg(request,"IAM.ZOHO.ACCOUNTS"));
      out.write("</title>\n");
      out.write("		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("		");
      out.print( HtmlResourceIncluder.addResource("/v2/components/css/zohoPuvi.css") );
      out.write("</head>\n");
      out.write("		<style>\n");
      out.write("		body {\n");
      out.write("			width: 100%;\n");
      out.write("			margin: 0px;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.container {\n");
      out.write("			display: block;\n");
      out.write("			width: 70%;\n");
      out.write("			margin: auto;\n");
      out.write("			margin-top: 120px;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.zoho_logo {\n");
      out.write("			display: block;\n");
      out.write("			margin: auto;\n");
      out.write("			height: 40px;\n");
      out.write("			max-width: 200px;\n");
      out.write("			width: auto;\n");
      out.write("			background: url(\"");
      out.print(StaticContentLoader.getStaticFilePath("/v2/components/images/newZoho_logo.svg"));
      out.write("\") no-repeat transparent;\n");
      out.write("			margin-bottom: 40px;\n");
      out.write("			background-position: center;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.error_img {\n");
      out.write("			display: block;\n");
      out.write("			height: 300px;\n");
      out.write("			margin-bottom: 40px;\n");
      out.write("			width: 100%;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.raodblock {\n");
      out.write("			background: url(");
      out.print(StaticContentLoader.getStaticFilePath("/v2/components/images/roadblock.png"));
      out.write(") no-repeat transparent;\n");
      out.write("			background-size: auto 100%;\n");
      out.write("			background-position: center;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.heading {\n");
      out.write("			display: block;\n");
      out.write("			text-align: center;\n");
      out.write("			font-size: 24px;\n");
      out.write("			margin-bottom: 10px;\n");
      out.write("			line-height: 34px;\n");
      out.write("			font-weight: 600;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.discrption {\n");
      out.write("			display: block;\n");
      out.write("			width: 500px;\n");
      out.write("			margin: auto;\n");
      out.write("			text-align: center;\n");
      out.write("			font-size: 16px;\n");
      out.write("			margin-bottom: 10px;\n");
      out.write("			line-height: 24px;\n");
      out.write("			color: #444;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.refresh_btn {\n");
      out.write("		   	background-color: #1389E3;\n");
      out.write("		    color: #fff;\n");
      out.write("		    padding: 12px 30px;\n");
      out.write("		    border-radius: 5px;\n");
      out.write("		    font-size: 14px;\n");
      out.write("		    cursor: pointer;\n");
      out.write("			width: fit-content;\n");
      out.write("		    width: -moz-fit-content;\n");
      out.write("		    width: -webkit-fit-content;\n");
      out.write("		    font-weight: 600;\n");
      out.write("		    margin: auto;\n");
      out.write("		    margin-top: 30px;\n");
      out.write("		}\n");
      out.write("		.logout-wrapper {\n");
      out.write("		    position: absolute;\n");
      out.write("		    top: 25px;\n");
      out.write("		    right: 50px;\n");
      out.write("		    cursor: pointer;\n");
      out.write("		    border: solid 1px #fff;\n");
      out.write("		    border-radius: 8px;\n");
      out.write("		    font-family: 'ZohoPuvi', 'Open Sans', sans-serif;\n");
      out.write("		    font-size: 14px;\n");
      out.write("		    transition: .3s width, .3s height;    \n");
      out.write("		    z-index: 1;\n");
      out.write("		    overflow:hidden;\n");
      out.write("		}\n");
      out.write("		.logout-wrapper:hover {\n");
      out.write("		    border-color: #e0e0e0;\n");
      out.write("		    background-color: #fbfcfc;\n");
      out.write("		}\n");
      out.write("		.logout-wrapper .name {\n");
      out.write("			position: absolute;\n");
      out.write("		    top: 0px;\n");
      out.write("		    right: 38px;\n");
      out.write("		    margin: 0;\n");
      out.write("		    line-height: 30px;\n");
      out.write("		    display: block;\n");
      out.write("		    transition: right .3s ease-out,top .3s ease-out;\n");
      out.write("		    white-space:nowrap;\n");
      out.write("		}\n");
      out.write("		.logout-wrapper img {\n");
      out.write("		    width: 30px;\n");
      out.write("		    height: 30px;\n");
      out.write("		    position: absolute;\n");
      out.write("		    right: 0px;\n");
      out.write("		    top: 0px;\n");
      out.write("		    transition: all .3s ease-out;     \n");
      out.write("		    border-radius: 50%;     \n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.logout-wrapper.open .name {\n");
      out.write("		    font-size: 16px;\n");
      out.write("		    font-weight: 500;\n");
      out.write("		    top: 116px;\n");
      out.write("		    line-height: 20px;\n");
      out.write("		    text-overflow: unset;\n");
      out.write("		    overflow:unset;\n");
      out.write("		    width:260px;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.logout-wrapper.open img {\n");
      out.write("		    width: 80px;\n");
      out.write("		    height: 80px;\n");
      out.write("		    top: 20px;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.logout-wrapper.open {\n");
      out.write("		    border-color: #e0e0e0;\n");
      out.write("		    background-color: #fbfcfc;\n");
      out.write("		    box-shadow: 0px 0px 6px 8px #ececec85;   \n");
      out.write("		}\n");
      out.write("		p.muted {\n");
      out.write("		    font-size: 12px;\n");
      out.write("		    line-height: 14px;\n");
      out.write("		    color: #5b6367;\n");
      out.write("		    margin:0px;\n");
      out.write("		    padding-top: 8px;\n");
      out.write("		}\n");
      out.write("		div.dc {\n");
      out.write("		    padding: 10px 25px;\n");
      out.write("		    background: #ffffff;\n");
      out.write("		    border-top: solid 1px #e0e0e0;\n");
      out.write("		    border-radius: 0px 0px 8px 8px;\n");
      out.write("		    font-size: 10px;\n");
      out.write("		    color: #5b6367;\n");
      out.write("		    line-height: 16px;\n");
      out.write("		    white-space: nowrap;\n");
      out.write("		}\n");
      out.write("		div.dc span {\n");
      out.write("		    font-size: 16px;\n");
      out.write("		    margin-right: 6px;\n");
      out.write("		    vertical-align: middle;\n");
      out.write("		    line-height: 1;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		a.err-btn {\n");
      out.write("		    background-color: #EF5E57;\n");
      out.write("		    cursor: pointer;\n");
      out.write("		    width: fit-content;\n");
      out.write("		    width: -moz-fit-content;\n");
      out.write("		    width: -webkit-fit-content;\n");
      out.write("		    font-weight: 500;\n");
      out.write("		    color: #fff;\n");
      out.write("		    padding: 10px 30px;\n");
      out.write("		    border-radius: 5px;\n");
      out.write("		    font-size: 12px;\n");
      out.write("		    border: none;\n");
      out.write("		    margin: 20px auto;\n");
      out.write("		    font-family: 'ZohoPuvi', 'Open Sans', sans-serif;\n");
      out.write("		    text-decoration: none;\n");
      out.write("		    display: block;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		a.err-btn:focus, a.err-btn:focus-visible {\n");
      out.write("			outline: none;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.user-info {\n");
      out.write("		    position: absolute;\n");
      out.write("		    top: 0px;\n");
      out.write("		    right: 0px;\n");
      out.write("		    height: 30px;\n");
      out.write("		    margin: 8px 24px;\n");
      out.write("		    /* transition: all .3s; */\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.more-info {\n");
      out.write("		    position: absolute;\n");
      out.write("		    visibility: hidden;\n");
      out.write("		    top: 0px;\n");
      out.write("		    text-align: center;\n");
      out.write("		    transition: top .3s;    \n");
      out.write("		    width: 100%;\n");
      out.write("		    display: table;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.logout-wrapper.open .more-info {\n");
      out.write("		    visibility: visible;\n");
      out.write("		    top: 138px;\n");
      out.write("		    right: 0px;\n");
      out.write("		    min-width:300px;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.logout-wrapper.open .user-info {\n");
      out.write("		    margin:0px;\n");
      out.write("		    width:300px;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.text-ellipsis{\n");
      out.write("			width:160px;\n");
      out.write("			text-overflow:ellipsis;\n");
      out.write("			overflow:hidden;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.text-ellipsis-withoutWidth{\n");
      out.write("			text-overflow:ellipsis;\n");
      out.write("			overflow:hidden;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.logout-wrapper.open .name.white-spaces{\n");
      out.write("			white-space: break-spaces;\n");
      out.write("			text-align:center;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.max-width{\n");
      out.write("			max-width:260px;\n");
      out.write("		}\n");
      out.write("\n");
      out.write("		@media only screen and (-webkit-min-device-pixel-ratio: 2) , only screen and (\n");
      out.write("				min--moz-device-pixel-ratio: 2) , only screen and (\n");
      out.write("				-o-min-device-pixel-ratio: 2/1) , only screen and (\n");
      out.write("				min-device-pixel-ratio: 2) , only screen and ( min-resolution: 192dpi)\n");
      out.write("				, only screen and ( min-resolution: 2dppx) {\n");
      out.write("			.raodblock {\n");
      out.write("				background: url(");
      out.print(StaticContentLoader.getStaticFilePath("/v2/components/images/roadblock@2x.png"));
      out.write(") no-repeat transparent;\n");
      out.write("				background-size: auto 100%;\n");
      out.write("				background-position: center;\n");
      out.write("			}\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		@media only screen and (max-width: 500px) {\n");
      out.write("			.container {\n");
      out.write("				width: 90%;\n");
      out.write("				margin-top: 80px;\n");
      out.write("			}\n");
      out.write("			.discrption {\n");
      out.write("				width: 100%;\n");
      out.write("			}\n");
      out.write("			.error_img {\n");
      out.write("				display: block;\n");
      out.write("				max-width: 340px;\n");
      out.write("				background-size: 100% auto;\n");
      out.write("				margin: auto;\n");
      out.write("				margin-bottom: 40px;\n");
      out.write("			}\n");
      out.write("			.heading {\n");
      out.write("				display: block;\n");
      out.write("				text-align: center;\n");
      out.write("				font-size: 20px;\n");
      out.write("				margin-bottom: 10px;\n");
      out.write("				line-height: 30px;\n");
      out.write("				font-weight: 600;\n");
      out.write("			}\n");
      out.write("			.discrption {\n");
      out.write("				display: block;\n");
      out.write("				margin: auto;\n");
      out.write("				text-align: center;\n");
      out.write("				font-size: 14px;\n");
      out.write("				margin-bottom: 10px;\n");
      out.write("				line-height: 24px;\n");
      out.write("				color: #444;\n");
      out.write("			}\n");
      out.write("			.user-info{\n");
      out.write("				margin:8px 12px;\n");
      out.write("			}\n");
      out.write("			.logout-wrapper{\n");
      out.write("				top:20px;\n");
      out.write("				right:10px;\n");
      out.write("			}\n");
      out.write("			.logout-wrapper{\n");
      out.write("				position : absolute;\n");
      out.write("			}\n");
      out.write("			.text-ellipsis{\n");
      out.write("				width:130px;\n");
      out.write("			}\n");
      out.write("			.logout-wrapper:hover {\n");
      out.write("			    border-color: transparent;\n");
      out.write("		    	background-color: unset;\n");
      out.write("			}\n");
      out.write("			.logout-wrapper.open {\n");
      out.write("			    border-color: #e0e0e0;\n");
      out.write("			    background-color: #fbfcfc;\n");
      out.write("			}\n");
      out.write("		}\n");
      out.write("		</style>\n");
      out.write("		\n");
      out.write("		<body>\n");
      out.write("			");
 if(ClientPortalUtil.isClientServer()){ 
      out.write("<div class=\"container\"> \n");
      out.write("				<div class=\"error_img raodblock\"></div>\n");
      out.write("				<div class=\"heading\">");
      out.print(errorTitle);
      out.write("</div>\n");
      out.write("				<div class=\"discrption\">");
      out.print(errorDescryption);
      out.write("</div>\n");
      out.write("			</div>\n");
      out.write("		</body>\n");
      out.write("			");
}else{
      out.write("<div class=\"logout-wrapper hide\">\n");
      out.write("				<div class=\"user-info\">\n");
      out.write("					<p class=\"name\"></p>\n");
      out.write("					<img src=\"");
      out.print(StaticContentLoader.getStaticFilePath("/v2/components/images/user_2.png") );
      out.write("\" />\n");
      out.write("				</div>\n");
      out.write("				<div class=\"more-info\">\n");
      out.write("					<p id=\"user-email\"class=\"muted\"></p>\n");
      out.write("					<a href=\"");
      out.print( IAMEncoder.encodeHTMLAttribute(Util.getCurrentLogoutURL(request, AccountsConstants.ACCOUNTS_SERVICE_NAME,"")) );
      out.write("\" class=\"err-btn\">");
      out.print( Util.getI18NMsg(request,"IAM.SIGN.OUT"));
      out.write("</a> \n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"container\"> \n");
      out.write("				<div class=\"zoho_logo\"></div>\n");
      out.write("				<div class=\"error_img raodblock\"></div>\n");
      out.write("				<div class=\"heading\">");
      out.print(errorTitle);
      out.write("</div>\n");
      out.write("				<div class=\"discrption\">");
      out.print(errorDescryption);
      out.write("</div>\n");
      out.write("				");
 if(!hideHomeRedirection){
      out.write("<div class=\"refresh_btn\"id=\"home_redirection\" onclick=\"location.href='/'\">");
      out.print( Util.getI18NMsg(request,"IAM.GOTO.HOME"));
      out.write("</div>\n");
      out.write("				");
} 
      out.write("</div>\n");
      out.write("			<footer id=\"footer\"> ");
      out.write("<style>\n");
      out.write("		#footer\n");
      out.write("		{	\n");
      out.write("		    width: 100%;\n");
      out.write("		    height: 20px;\n");
      out.write("		    font-size: 14px;\n");
      out.write("		    color: #727272;\n");
      out.write("		   	position:absolute;\n");
      out.write("		   	left:0px;\n");
      out.write("		   	right:0px;\n");
      out.write("		    margin:20px auto;\n");
      out.write("		    text-align:center;\n");
      out.write("		    font-size: 14px;\n");
      out.write("		    bottom: 0px;\n");
      out.write("		}\n");
      out.write("		#footer a\n");
      out.write("		{\n");
      out.write("		    text-decoration:none;\n");
      out.write("		    color: #727272;\n");
      out.write("		    font-size: 14px;\n");
      out.write("		}\n");
      out.write("		@media only screen and (max-width: 435px) {\n");
      out.write("			#footer a,#footer,footer{	\n");
      out.write("				font-size: 12px !important;\n");
      out.write("			}\n");
      out.write("		}\n");
      out.write("		</style>\n");
      out.write("			<div style=\"padding:5px 0px;\">\n");
      out.write("				<span>\n");
      out.write("					");
      out.print(Util.getI18NMsg(request,"IAM.ZOHOCORP.FOOTER", Util.getCopyRightYear(), Util.getI18NMsg(request,"IAM.ZOHOCORP.LINK")));
      out.write("</span>\n");
      out.write("			</div>");
      out.write("</footer> ");
      out.write("</body>\n");
      out.write("		<script>\n");
      out.write("			function setFooterPosition(){\n");
      out.write("				var container = document.getElementsByClassName(\"container\")[0];\n");
      out.write("				var top_value = window.innerHeight-60;\n");
      out.write("				if(container && (container.offsetHeight+container.offsetTop+30)<top_value){\n");
      out.write("					document.getElementById(\"footer\").style.top = top_value+\"px\"; // No I18N\n");
      out.write("				}\n");
      out.write("				else{\n");
      out.write("					document.getElementById(\"footer\").style.top = container && (container.offsetHeight+container.offsetTop+30)+\"px\"; // No I18N\n");
      out.write("				}\n");
      out.write("			}\n");
      out.write("			window.addEventListener(\"resize\",function(){\n");
      out.write("				setFooterPosition();\n");
      out.write("			});\n");
      out.write("			window.addEventListener(\"load\",function(){\n");
      out.write("				setFooterPosition();\n");
      out.write("				");
if(showLogout){
      out.write("\n");
      out.write("					showLogout();\n");
      out.write("				");
}
      out.write("\n");
      out.write("			});\n");
      out.write("			");
if(showLogout){
      out.write("\n");
      out.write("				var checkIsMobile = false;\n");
      out.write("				");
if(Util.isMobileUserAgent(request)){
      out.write("\n");
      out.write("					checkIsMobile = true;\n");
      out.write("				");
}
      out.write("			    			\n");
      out.write("				var logWrap = document.querySelector('.logout-wrapper');	// No I18N\n");
      out.write("				var userWrap = document.querySelector('.logout-wrapper .user-info');	// No I18N\n");
      out.write("				var moreWrap = document.querySelector('.logout-wrapper .more-info');	// No I18N\n");
      out.write("				var nameDom = userWrap.querySelector('p');								// No I18N\n");
      out.write("				var imageWrap = document.querySelector('.logout-wrapper .user-info img');	// No I18N\n");
      out.write("				var overflow =false;\n");
      out.write("				var initialMaxWidth = checkIsMobile ? 130 : 160;\n");
      out.write("				var nameWidth = nameDom.offsetWidth;\n");
      out.write("			");
}
      out.write("\n");
      out.write("			function xhr() {\n");
      out.write("			    var xmlhttp;\n");
      out.write("			    if (window.XMLHttpRequest) {\n");
      out.write("					xmlhttp=new XMLHttpRequest();\n");
      out.write("			    } else if(window.ActiveXObject) {\n");
      out.write("					try {\n");
      out.write("					    xmlhttp=new ActiveXObject(\"Msxml2.XMLHTTP\");\n");
      out.write("					}\n");
      out.write("					catch(e) {\n");
      out.write("					    xmlhttp=new ActiveXObject(\"Microsoft.XMLHTTP\");\n");
      out.write("					}\n");
      out.write("			    }\n");
      out.write("			    return xmlhttp;\n");
      out.write("			}\n");
      out.write("			function showLogout(){\n");
      out.write("				var objHTTP = xhr();\n");
      out.write("			   	objHTTP.open('GET', '/u/unauth/info', true);\n");
      out.write("				objHTTP.onreadystatechange=function() {\n");
      out.write("			    	if(objHTTP.readyState==4 && objHTTP.status === 200 ) {\n");
      out.write("			    		var info = objHTTP.responseText && JSON.parse(objHTTP.responseText);\n");
      out.write("			    		if(info && info.EMAIL_ID && info.DISPLAY_NAME){\n");
      out.write("			    			nameDom.innerHTML = info.DISPLAY_NAME;\n");
      out.write("			    			if(nameDom.offsetWidth > initialMaxWidth  ){\n");
      out.write("			    				overflow=true;\n");
      out.write("			    				nameDom.classList.add(\"text-ellipsis\");	// No I18N\n");
      out.write("			    			}\n");
      out.write("					    	moreWrap.querySelector('#user-email').innerHTML = info.EMAIL_ID; // No I18N\n");
      out.write("					    	nameWidth = nameDom.offsetWidth;\n");
      out.write("			    			moreWrap.setAttribute('style','top:80px');\n");
      out.write("			    			userWrap.setAttribute('style','width:'+(nameDom.offsetWidth + 38)+'px;height:'+nameDom.offsetHeight+'px');\n");
      out.write("			    			if(checkIsMobile && window.innerWidth <= 500 ){\n");
      out.write("			    					nameDom.setAttribute('style','width:'+nameWidth+'px;height:'+(nameDom.offsetHeight)+'px;');\n");
      out.write("	    							userWrap.setAttribute('style','width:'+30+'px;height:'+nameDom.offsetHeight+'px');\n");
      out.write("	    							logWrap.setAttribute('style','width:'+(userWrap.offsetWidth + 24)+'px;height:'+(userWrap.offsetHeight+16)+'px;');\n");
      out.write("			    					nameDom.style.display=\"none\";\n");
      out.write("			    			}\n");
      out.write("			    			else{\n");
      out.write("			    				logWrap.setAttribute('style','width:'+(userWrap.offsetWidth + 48)+'px;height:'+(userWrap.offsetHeight+16)+'px');	\n");
      out.write("			    			}\n");
      out.write("					    	logWrap.addEventListener('click', function(event) {\n");
      out.write("					    		event.stopPropagation();\n");
      out.write("					    		if(!event.target.classList.contains('err-btn')) {\n");
      out.write("					    			logWrap.classList.toggle('open');	// No I18N\n");
      out.write("					    			if(logWrap.classList.contains('open')) {\n");
      out.write("					    				var fullWidth =300;\n");
      out.write("					    				nameDom.style.display=\"block\";\n");
      out.write("					    				nameDom.classList.remove(\"text-ellipsis\");	// No I18N\n");
      out.write("					    				nameDom.style.width=(fullWidth-40)+'px';\n");
      out.write("					    				nameDom.style.right =\"20px\";	// No I18N\n");
      out.write("					    				nameDom.classList.add(\"white-spaces\");	// No I18N\n");
      out.write("					    				imageWrap.style.right = ((moreWrap.offsetWidth/2) - 40) + \"px\";	// No I18N\n");
      out.write("					    				userWrap.setAttribute('style','width:'+fullWidth+'px;height:'+(138+(nameDom.offsetHeight-20))+'px');\n");
      out.write("					    				moreWrap.setAttribute('style','top:'+(138+(nameDom.offsetHeight-20))+'px;transition:all .3s ease-out');\n");
      out.write("					    				logWrap.setAttribute('style','width:'+fullWidth+'px;height:'+(userWrap.offsetHeight + moreWrap.offsetHeight)+'px');\n");
      out.write("					    			} else {\n");
      out.write("					    				moreWrap.setAttribute('style','top:80px;transition:none');\n");
      out.write("					    				nameDom.style.right = '38px';	// No I18N\n");
      out.write("					    				imageWrap.style.right = '0px';	// No I18N\n");
      out.write("					    				if(overflow){\n");
      out.write("					    					nameDom.style.width = \"160px\";\n");
      out.write("					    					nameDom.classList.add(\"text-ellipsis\");	// No I18N\n");
      out.write("					    				}\n");
      out.write("					    				else{\n");
      out.write("					    					nameDom.style.width = nameWidth + 'px';\n");
      out.write("					    				}\n");
      out.write("					    				nameDom.classList.remove(\"white-spaces\");	// No I18N\n");
      out.write("					    				userWrap.setAttribute('style','width:'+(nameDom.offsetWidth + 38)+'px;height:'+nameDom.offsetHeight+'px');\n");
      out.write("					    				if(checkIsMobile && window.innerWidth <= 500){\n");
      out.write("						    					nameDom.setAttribute('style','width:'+nameWidth+'px;height:'+(nameDom.offsetHeight)+'px;');\n");
      out.write("				    							userWrap.setAttribute('style','width:'+30+'px;height:'+nameDom.offsetHeight+'px');\n");
      out.write("				    							logWrap.setAttribute('style','width:'+(userWrap.offsetWidth + 24)+'px;height:'+(userWrap.offsetHeight+16)+'px;');\n");
      out.write("					    						nameDom.style.display=\"none\";\n");
      out.write("					    				}\n");
      out.write("					    				else{\n");
      out.write("					    					logWrap.setAttribute('style','width:'+(userWrap.offsetWidth + 48)+'px;height:'+(userWrap.offsetHeight+16)+'px');	\n");
      out.write("					    				}\n");
      out.write("					    			}\n");
      out.write("					    		}\n");
      out.write("					    	});\n");
      out.write("					    	document.addEventListener('click', function(event) {\n");
      out.write("					    		if(!event.target.classList.contains('err-btn') && logWrap.classList.contains('open')) {\n");
      out.write("					    			moreWrap.setAttribute('style','top:80px');\n");
      out.write("					    			logWrap.classList.toggle('open');	// No I18N\n");
      out.write("					    			nameDom.style.right = '38px';		// No I18N\n");
      out.write("					    			imageWrap.style.right = '0px';		// No I18N\n");
      out.write("					    			if(overflow){\n");
      out.write("					    				nameDom.style.width = \"160px\";\n");
      out.write("					    				nameDom.classList.add(\"text-ellipsis\");	// No I18N\n");
      out.write("					    			}\n");
      out.write("					    			else{\n");
      out.write("					    				nameDom.style.width = nameWidth + 'px';\n");
      out.write("					    			}\n");
      out.write("					    			\n");
      out.write("					    			nameDom.classList.remove(\"white-spaces\");	// No I18N\n");
      out.write("					    			userWrap.setAttribute('style','width:'+(nameDom.offsetWidth + 38)+'px;height:'+nameDom.offsetHeight+'px');\n");
      out.write("					    			if(checkIsMobile && window.innerWidth <= 500){\n");
      out.write("					    					nameDom.setAttribute('style','width:'+nameWidth+'px;height:'+(nameDom.offsetHeight)+'px;');\n");
      out.write("			    							userWrap.setAttribute('style','width:'+30+'px;height:'+nameDom.offsetHeight+'px');\n");
      out.write("			    							logWrap.setAttribute('style','width:'+(userWrap.offsetWidth + 24)+'px;height:'+(userWrap.offsetHeight+16)+'px;');\n");
      out.write("					    					nameDom.style.display=\"none\";\n");
      out.write("					    			}\n");
      out.write("					    			else{\n");
      out.write("					    				logWrap.setAttribute('style','width:'+(userWrap.offsetWidth + 48)+'px;height:'+(userWrap.offsetHeight+16)+'px');	\n");
      out.write("					    			}\n");
      out.write("					    		}\n");
      out.write("					    	});\n");
      out.write("			    		}\n");
      out.write("			    	}\n");
      out.write("				};\n");
      out.write("			   	objHTTP.send();\n");
      out.write("			}\n");
      out.write("		</script>\n");
      out.write("			");
 } 
      out.write("</html>\n");

	}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
